import { chromium } from '@playwright/test';
const browser = await chromium.launch();
const page = await browser.newPage();
const errors = [];
page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
page.on('pageerror', e => errors.push('PAGEERROR: ' + e.message));
await page.goto('http://localhost:4173/', { waitUntil: 'domcontentloaded' }).catch(e => errors.push('GOTO: '+e.message));
await page.waitForTimeout(3000);
console.log(errors.slice(0, 10).join('\n---\n') || 'no errors');
await browser.close();
