#!/usr/bin/env bash
# deploy-android.sh — build a release APK and copy it to the web root
# alongside the existing /android link. Usage:
#
#   ./scripts/deploy-android.sh                 # build a release APK
#   ./scripts/deploy-android.sh --aab           # build an AAB for Play
#   ./scripts/deploy-android.sh --base https://app.topodrive.top/
#
# Requires: JDK 17+, ANDROID_HOME with build-tools 34 + platform 34,
# and a `signing.properties` in the android/ root (see README).

set -euo pipefail

ANDROID_DIR="$(cd "$(dirname "$0")/.." && pwd)"
APP_DIR="${ANDROID_DIR}/app"
OUT_HTML="/var/www/app.topodrive.top"
DOWNLOAD_HTML="${OUT_HTML}/android.html"
GRADLE="./gradlew"

if [[ ! -x "${ANDROID_DIR}/gradlew" ]]; then
  echo "ERROR: gradlew not found at ${ANDROID_DIR}/gradlew" >&2
  exit 1
fi

cd "${ANDROID_DIR}"

ARGS=()
ARTIFACT_KIND="apk"
BASE_URL="https://app.topodrive.top/"
for a in "$@"; do
  case "$a" in
    --aab) ARTIFACT_KIND="aab" ;;
    --base) shift; BASE_URL="${1:-}"; ARGS+=("-PBASE_URL=${BASE_URL}") ;;
    *) ARGS+=("$a") ;;
  esac
done

if [[ "${ARTIFACT_KIND}" == "aab" ]]; then
  echo "→ Building AAB…"
  "${GRADLE}" :app:bundleRelease "${ARGS[@]}"
  ARTIFACT="${APP_DIR}/build/outputs/bundle/release/app-release.aab"
else
  echo "→ Building APK…"
  "${GRADLE}" :app:assembleRelease "${ARGS[@]}"
  ARTIFACT="${APP_DIR}/build/outputs/apk/release/app-release.apk"
fi

if [[ ! -f "${ARTIFACT}" ]]; then
  echo "ERROR: artifact not produced at ${ARTIFACT}" >&2
  exit 2
fi

VERSION_NAME=$(grep -oP 'versionName\s*=\s*"\K[^"]+' "${APP_DIR}/build.gradle.kts" | head -1)
VERSION_CODE=$(grep -oP 'versionCode\s*=\s*\K[0-9]+' "${APP_DIR}/build.gradle.kts" | head -1)
SHA256=$(sha256sum "${ARTIFACT}" | cut -d' ' -f1)
SIZE=$(stat -c%s "${ARTIFACT}")
BASE_NAME="socrates-${VERSION_NAME}-${VERSION_CODE}"

echo "✓ Built: ${ARTIFACT}"
echo "  size:    ${SIZE} bytes"
echo "  sha256:  ${SHA256}"
echo "  base:    ${BASE_URL}"

# Copy the APK into a publicly-served location so the landing page can
# offer a "Download for Android" link. We name it with the version so
# the file is stable across rebuilds.
sudo mkdir -p "${OUT_HTML}/downloads"
DEST="${OUT_HTML}/downloads/${BASE_NAME}.apk"
sudo install -m 644 -o www-data -g www-data "${ARTIFACT}" "${DEST}"

# Also keep "latest" symlink in sync so the static page can point at a
# single URL.
sudo ln -sfn "${BASE_NAME}.apk" "${OUT_HTML}/downloads/socrates-latest.apk"
sudo ls -l "${OUT_HTML}/downloads" | head -20

# Touch the static download page so the change shows up in the SPA
# wrapper. We don't rewrite index.html — the Android landing lives in
# /android (a separate route) and is regenerated by a static template.
if [[ -f "${ANDROID_DIR}/scripts/download-page.tpl.html" ]]; then
  sudo -E bash -c "
    BASE_URL='${BASE_URL}' \
    VERSION_NAME='${VERSION_NAME}' \
    VERSION_CODE='${VERSION_CODE}' \
    SHA256='${SHA256}' \
    SIZE='${SIZE}' \
    envsubst < '${ANDROID_DIR}/scripts/download-page.tpl.html' \
      > '${DOWNLOAD_HTML}.tmp' && \
    install -m 644 -o www-data -g www-data '${DOWNLOAD_HTML}.tmp' '${DOWNLOAD_HTML}' && \
    rm '${DOWNLOAD_HTML}.tmp'
  "
fi

# Cheap health check — make sure the nginx server still answers.
if command -v curl >/dev/null 2>&1; then
  echo "  served:  $(curl -s -o /dev/null -w '%{http_code}' --max-time 5 "${BASE_URL}android")"
  echo "  apk url: ${BASE_URL}downloads/socrates-latest.apk"
fi
