/* chat/editBranch.js — extracted from main.js (B5 batch).
 * Edit / regenerate / branch operations. Zero-behavior-change lift.
 * Main.js-local turn entries (askChatTurn, saveCurrentSession, resetApp)
 * resolve via window.* at call time to avoid circular imports.
 */
import { stateStore } from '../state/store.js';
import { turnState } from './turnState.js';
import { quietTurn } from './turnUi.js';
import {
  findMessageIndex,
  messageApiPath,
  restoreMessageBody,
  rollbackMessagesAfter,
} from '../ui/messageActions.ts';
import { stripMarkdown, formatMsg } from '../render/markdown.js';
import { buildUserContentParts } from '../chat/history.js';
import { apiFetch } from '../util/api.js';
import { showToast } from '../ui/toast.js';
import { publishReactChatRuntime } from '../ui/reactBridge.js';

function _t(key) {
  try {
    if (typeof window !== 'undefined' && typeof window.t === 'function') return window.t(key);
  } catch (_) {}
  return key;
}
function _saveCurrentSession() {
  try { if (typeof window.saveCurrentSession === 'function') window.saveCurrentSession(); } catch (_) {}
}
function _resetApp() {
  return (typeof window.resetApp === 'function') ? window.resetApp() : Promise.resolve(false);
}

export function editUserMessage(messageId){
  var idx=findMessageIndex(messageId);
  if(idx<0){showToast(_t("toast.messageNotFound"));return}
  var entry=stateStore.read("messages")[idx];
  var div=document.querySelector('[data-client-id="'+messageId+'"]');
  if(!div){return}
  var body=div.querySelector(".msg-body");
  if(!body){return}
  /* Swap the rendered body for a textarea, preserving width.
     Show plain text only — strip markdown formatting symbols so
     the user edits clean content without **bold**, *italic*, etc. */
  var ta=document.createElement("textarea");
  ta.className="msg-edit-area";
  ta.value=stripMarkdown(entry.rawText||"");
  body.innerHTML="";
  body.appendChild(ta);
  ta.focus();
  ta.setSelectionRange(ta.value.length,ta.value.length);
  function commit(){
    var next=ta.value.trim();
    if(!next||next===entry.rawText){
      /* No change — restore. */
      restoreMessageBody(entry,body);
      return;
    }
    /* P_edit — "edit a message" means "roll the conversation back
       to here and replay from this turn". Any assistant / user /
       system messages that followed this turn no longer make sense
       once the user turn is different, so we drop them from the
       authoritative state + the DOM before re-sending. */
    var editedText=next;
    entry.rawText=editedText;
    entry.html=null;
    restoreMessageBody(entry,body);
    rollbackMessagesAfter(messageId);
    /* PATCH /api/messages/<id>?regenerate=false&discardFollowing=true
       — server updates the user turn in place AND deletes any later
       assistant / user rows it had previously stored, so a hard
       reload after the edit doesn't surface stale replies. The
       local state is already trimmed; this keeps the server in
       sync. The actual answer is generated by the normal chat stream
       below, which is the single path that owns native tools. */
    var patchPromise=apiFetch(messageApiPath(messageId),{
      method:"PATCH",
      body:{content:editedText,regenerate:false,discardFollowing:true},
    }).catch(function(e){
      /* A just-created local message may not have reached the session
         upsert yet. The local state remains authoritative and the next save
         will persist it, so do not turn that expected 404 into an error toast. */
      if(!e||e.status!==404){
        console.log("[msg-edit] PATCH failed");
        showToast(_t("toast.savedOffline"));
      }
    });
    /* P0.1 BUG-P01-03 — if the edited message carried image / PDF /
       text attachments, rebuild the multimodal content parts and stash
       them on turnState.pendingChatContent so the resend still includes
       the attachments. After the previous send this global is null
       (cleared post-send), so without this the edited turn would
       degrade to text-only even though extractHistory can rebuild the
       parts — askChatTurn slices the trailing user history entry and
       sends turnState.pendingChatContent (or the plain text fallback) instead.
       A text-only edit yields null → askChatTurn falls back to text. */
    try{ turnState.pendingChatContent=buildUserContentParts(editedText,entry.attachments); }catch(_){ turnState.pendingChatContent=null; }
    /* Replay from the edited turn. askChatTurn writes a fresh
       streaming assistant bubble into the now-empty tail of the
       conversation. P0.1 NOTE-P01-06 — start the new turn only AFTER
       the PATCH settles. discardFollowing deletes assistant rows with
       createdAt >= this user turn; the regenerated reply also gets
       createdAt = now, so if the server delete landed AFTER the fresh
       reply was saved it would wipe the new answer. Chaining the re-ask
       on patchPromise (which resolves even on failure via .catch) closes
       that window — the sub-second PATCH is imperceptible against model
       latency, and the abort below stops any in-flight stream at once. */
    if(typeof window.askChatTurn==="function"){
      /* If a stream is already in flight (e.g. user clicked edit
         while the previous reply was still arriving), abort it
         first so the new turn isn't racing the old one. */
      if(turnState.activeChatCtl){try{turnState.activeChatCtl.abort()}catch(_){}}
      if(window._activeChatAbort){try{window._activeChatAbort("msg-edit")}catch(_){}}
      patchPromise.then(function(){
        try{ quietTurn(window.askChatTurn(editedText)); }catch {/* msg-edit replay failed */}
      });
    }
    /* Avoid leaving the patch promise dangling — reference it so
       linters don't drop it. */
    void patchPromise;
  }
  ta.addEventListener("blur",commit);
  ta.addEventListener("keydown",function(ev){
    if(ev.key==="Enter"&&(ev.metaKey||ev.ctrlKey)){
      ev.preventDefault();
      ta.blur();
    }else if(ev.key==="Escape"){
      ev.preventDefault();
      restoreMessageBody(entry,body);
    }
  });
}

/* P_edit — remove every message whose position in stateStore.read("messages")
   is greater than `userMessageId`. Removes both the state entry
   and its DOM node. Returns the number of messages dropped.
   Used by editUserMessage so the conversation "rewinds" to the
   edited turn before the new answer is generated. */
export function regenerateAssistantMessage(messageId){
  /* Hook into the existing streaming pipeline. Locate the user turn
     that produced this assistant reply, rewind the conversation to it
     (locally + server-side), then re-ask. */
  var assistantIdx=findMessageIndex(messageId);
  if(assistantIdx<0)return;
  var userIdx=assistantIdx-1;
  while(userIdx>=0&&stateStore.read("messages")[userIdx].role!=="user")userIdx--;
  var userEntry=userIdx>=0?stateStore.read("messages")[userIdx]:null;
  var userText=userEntry&&userEntry.rawText;
  if(!userText)return;
  var userMessageId=userEntry.clientId||userEntry.id;
  /* P0.1 BUG-P01-04 — rewind to the user turn instead of splicing only
     the single assistant bubble. Regenerating a reply invalidates every
     message that followed it, so drop them all from state + DOM (matches
     editUserMessage semantics). For the common case (the last assistant
     reply) this removes exactly that bubble; for a mid-conversation
     regenerate it prevents the new reply from being appended out of
     order after stale later turns. */
  rollbackMessagesAfter(userMessageId);
  /* P0.1 BUG-P01-02 — delete the replaced assistant rows server-side so
     a hard reload doesn't resurrect the stale reply. saveCurrentSession
     only upserts (never deletes rows absent from the payload), so the
     old assistant would otherwise persist as an orphan. Reuse the proven
     edit cleanup (PATCH …&discardFollowing) but with regenerate:false —
     the client re-asks locally via askChatTurn, so the server must NOT
     also generate a reply. Requires the user message to have a server
     UUID; a client-only id 400s and is caught (same limitation as edit,
     where the local rewind still holds until the next successful sync). */
  var patchPromise=Promise.resolve();
  if(userMessageId){
    patchPromise=apiFetch(messageApiPath(userMessageId),{
      method:"PATCH",
      body:{content:userText,regenerate:false,discardFollowing:true},
    }).catch(function(e){
      if(!e||e.status!==404)console.log("[msg-regen] server cleanup failed");
    });
  }
  /* P0.1 BUG-P01-03 (regenerate parity) — carry the original turn's
     attachments so a regenerate of a message that had an image / PDF /
     text doesn't degrade to text-only. Null for text-only turns. */
  try{ turnState.pendingChatContent=buildUserContentParts(userText,userEntry.attachments); }catch(_){ turnState.pendingChatContent=null; }
  if(typeof window.askChatTurn==="function"){
    /* Abort any in-flight stream so the regenerated turn isn't racing
       a previous reply that's still arriving. */
    if(turnState.activeChatCtl){try{turnState.activeChatCtl.abort()}catch(_){}}
    if(window._activeChatAbort){try{window._activeChatAbort("msg-regen")}catch(_){}}
    /* P0.1 NOTE-P01-06 — re-ask only AFTER the server discardFollowing
       settles, so the delete (assistant rows createdAt >= user turn)
       can't land after the fresh reply is saved and wipe it. Mirrors
       editUserMessage. patchPromise resolves even on failure (.catch). */
     patchPromise.then(function(){
       try{ quietTurn(window.askChatTurn(userText)); }catch {/* regen failed */}
     });
  }
}
/* Branch from a message — fork the conversation at this point.
   Saves the current session first, then creates a new session
   whose history only includes messages up to and including the
   branched message. The user can then continue in a different
   direction without affecting the original thread. */
export function branchFromMessage(messageId, opts){
  opts = opts || {};
  /* P1.1 — educational reExplain: when the branch is triggered by the
     re-explain button, inject a pedagogical directive into the system
     prompt so the model explains the topic from a different angle. */
  var reExplain = !!opts.reExplain;
  var branchIdx=findMessageIndex(messageId);
  if(branchIdx<0){showToast(_t("toast.messageNotFound"));return}
  /* Save the current session first so the original branch is
     persisted. */
  _saveCurrentSession();
  /* Build the new session state from messages up to this point.
     We copy the relevant fields from the current state. */
  var branchMessages=stateStore.read("messages").slice(0,branchIdx+1).map(function(m){
    return {clientId:m.clientId,role:m.role,rawText:m.rawText,html:m.html,type:m.type,attachments:Array.isArray(m.attachments)?m.attachments.slice(0,20):[]};
  });
  var branchTopic=stateStore.read("topic")||stateStore.read("topic")||"";
  var branchTitle=(stateStore.read("sessionTitle")||branchTopic)+" (branch)";
  /* P1.1 — branchedFrom metadata: record the source session id and
     the message id where the branch was taken, so the sidebar can
     display "Branched from ..." and the user can navigate back. */
  var branchedFrom = {
    sessionId: stateStore.read("currentSessionId") || stateStore.read("currentSessionId") || null,
    messageId: messageId,
    reExplain: reExplain,
  };
  /* Reset the app to a clean state, then inject the branched
     messages. We set a flag so the new session starts with the
     branch context instead of a blank topic. */
  var _branchContext={messages:branchMessages,topic:branchTopic,title:branchTitle,branchedFrom:branchedFrom};
  turnState.pendingBranchContext=_branchContext;
  /* Navigate to a new session. resetApp clears state, then we
     re-hydrate from the branch context. */
  _resetApp().then(function(resetProceeded){
    /* The new-session confirm can be cancelled; resetApp returns false in
       that case. Do NOT continue the branch (push messages / fire a turn)
       against the user's explicit choice. */
    if(resetProceeded===false){
      turnState.pendingBranchContext=null;
      return;
    }
    /* After resetApp completes, restore the branch context. */
    if(turnState.pendingBranchContext){
      var ctx=turnState.pendingBranchContext;
      turnState.pendingBranchContext=null;
      stateStore.dispatch({type:"session/replace-messages",payload:ctx.messages});
      stateStore.dispatch({type:"state/batch",patch:{
        topic:ctx.topic,
        sessionTitle:ctx.title,
        branchedFrom:ctx.branchedFrom||null
      }});
      /* React owns #msgList. Push a state-synced event so the React
         message list picks up the branched messages from the snapshot.
         The legacy DOM rebuild (innerHTML + per-msg divs + toolbars)
         was reachable only when msg-list was not migrated, which is no
         longer possible after the always-on React runtime landed. */
      publishReactChatRuntime({type:"state-synced",reason:"branch-context-restored"});
      /* Clear the greeting/topic setup so the user sees the
         branched conversation immediately. */
      var ts=document.getElementById("topicSetup");
      if(ts)ts.classList.add("hidden");
      var cv=document.getElementById("chatView");
      if(cv)cv.classList.remove("hidden");
      /* P1.1 — when reExplain is set, append a follow-up message that
         prompts the model to re-explain the last assistant message from
         a different angle. We push a short user message into the
         branched conversation so the model sees it on the next turn. */
      if(reExplain){
        var reExplainMsg = "Please re-explain that from a different angle. Use a different approach, analogy, or teaching method to help me understand better.";
        stateStore.dispatch({type:"session/append-message",payload:{
          clientId: "re-explain-" + Date.now(),
          role: "user",
          rawText: reExplainMsg,
          /* The React message list renders entry.html; without it the
             re-explain prompt appeared as an empty user bubble. */
          html: formatMsg(reExplainMsg),
          type: "text",
        }});
        publishReactChatRuntime({type:"state-synced",reason:"re-explain-prompt"});
        /* Fire the re-explain question immediately. */
        if(typeof window.askChatTurn === "function"){
          setTimeout(function(){ try{quietTurn(window.askChatTurn(reExplainMsg))}catch(_){} }, 100);
        }
      }
      _saveCurrentSession();
      showToast(reExplain ? "Re-explaining from a different angle" : "Branched from previous conversation");
    }
  });
}
