/* Shared UI strings for @socrates/ui (DOM-free). Components take an
 * optional `language` prop (default 'en'); the host app passes its settings
 * language down. Dictionaries live next to the components so labels never
 * drift from the markup that renders them. */

export type UiLanguage = 'en' | 'zh';

function en() {
  return {
    brand: 'Socrates',
    newChat: 'New chat',
    newExam: 'New exam',
    conversations: 'Conversations',
    untitled: 'Untitled',
    showArchived: (count: number) => `Show archived conversations (${count})`,
    hideArchived: 'Hide archived conversations',
    restoreSession: (title: string) => `Restore ${title}`,
    noArchived: 'No archived conversations.',
    emptyChat: 'How can I help you learn today?',
    messagePlaceholder: 'Ask Socrates',
    sendMessage: 'Send message',
    stopGenerating: 'Stop generating',
    attachPhotos: 'Attach photos',
    attachFile: 'Attach a file',
    takePhoto: 'Take a photo',
    removeAttachment: (name: string) => `Remove ${name}`,
    startVoiceInput: 'Start voice input',
    stopVoiceInput: 'Stop voice input',
    toggleReasoning: 'Toggle reasoning',
    reasoning: 'Reasoning',
    listenMessage: 'Read aloud',
    listen: '🔊 Listen',
    editMessage: 'Edit message',
    regenerateMessage: 'Regenerate response',
    branchMessage: 'Branch from here',
    copyCode: 'Copy code',
    copied: 'Copied',
    copyFailed: 'Copy failed',
    code: 'Code',
    codeExpand: (n: number) => `Show ${n} more lines`,
    codeCollapse: 'Show less',
    formula: 'Formula',
    notesTitle: 'Notes',
    toggleToolDetails: (name: string) => `Toggle ${name} details`,
    toolFailed: 'Failed',
    toolCompleted: 'Completed',
    toolRunning: 'Running',
    thinking: '…',
    openArtifact: (name: string) => `Open ${name} in the artifact island`,
    openInIsland: 'Open',
    visualization: 'Visualization',
    artifactSummary: 'Summary',
    closeViewer: 'Close preview',
    artifactError: 'This artifact could not be displayed.',
    openFile: (name: string) => `Open ${name}`,
    file: 'File',
    examTitle: 'Exam',
    examQuestionOf: (n: number, total: number) => `Question ${n} / ${total}`,
    examMultipleChoice: 'Multiple choice',
    examFillBlank: 'Fill blank',
    examShortAnswer: 'Short answer',
    examAnswerPlaceholder: 'Type your answer…',
    examSubmit: 'Submit exam',
    examMissingAnswers: 'Answer every question before submitting.',
    examAnsweredOf: (n: number, total: number) => `${n} / ${total} answered`,
    examScore: (correct: number, total: number, percent: number) => `${correct} / ${total} · ${percent}% correct`,
    examCorrect: 'Correct',
    examIncorrect: 'Incorrect',
    examExpected: 'Expected',
    examCorrectAnswer: 'Correct answer',
    examExplanation: 'Explanation',
    examSaved: 'Saved',
    modelTitle: 'Model',
    chooseModel: 'Choose model',
    filterModels: 'Filter models…',
    useModel: (name: string) => `Use ${name}`,
    manageModels: 'Manage models & keys',
    closeModelPicker: 'Close model picker',
    noModels: 'No models yet.',
    noModelMatches: 'No matches.',
    assistantTitle: 'Assistant',
    chooseAssistant: 'Choose assistant',
    filterAssistants: 'Filter assistants…',
    useAssistant: (name: string) => `Use ${name}`,
    manageAssistants: 'Manage assistants',
    closeAssistantPicker: 'Close assistant picker',
    noAssistants: 'No assistants yet.',
    noAssistantMatches: 'No matches.',
    noAssistant: 'No assistant',
    quizCorrect: (answer: string) => `Correct (${answer}).`,
    quizWrong: (answer: string) => `Not quite. The correct answer is ${answer}.`,
    quizRecorded: (letter: string) => `Recorded: ${letter}.`,
    quizPick: (letter: string, question: string) => `Answer ${letter} for ${question}`,
    showHint: 'Show hint',
    hideHint: 'Hide hint',
    revealAnswer: 'Reveal answer',
    submitAnswer: 'Submit',
    practicePlaceholder: 'Type your answer…',
    practiceEmpty: 'Please type an answer first.',
    practiceSent: 'Sent for review.',
    practiceSelfCorrect: 'Correct!',
    practiceSelfWrong: (answer: string) => `Not quite. The correct answer is: ${answer}`,
    scaffoldFallback: 'This content has a formatting issue; shown as-is.',
    diagTitle: 'Quick diagnostic',
    diagAnsweredOf: (n: number, total: number) => `${n} / ${total} answered`,
    diagOption: (question: string, letter: string) => `Answer ${letter} for ${question}`,
    diagSubmit: 'Start learning',
    diagMissing: 'Answer every question before continuing.',
    newTutor: 'New tutor',
    knowledge: 'Knowledge',
    mistakes: 'Mistakes',
    mistakeBook: 'Mistake Book',
    mistakesEmpty: 'No mistakes yet.',
    mistakesEmptyHint: 'Wrong quiz picks and incorrect practice attempts will land here for review.',
    mistakeTypeQuiz: 'Quiz',
    mistakeTypePractice: 'Practice',
    teachingPlan: 'Teaching plan',
    planProgress: (done: number, total: number, percent: number) => `${done} / ${total} (${percent}%)`,
    planDepth: (count: number) => `${Math.min(count, 3)}/3`,
    planDepthHint: 'Reach 3 in-depth answers to advance to the next sub-topic',
    planDone: '[done]',
    planStatusInternalized: 'Internalized',
    planStatusFuzzy: 'Fuzzy',
    planStatusBlank: 'Blank',
    noTeachingPlan: 'Complete a diagnostic to build a teaching plan.',
    planStageMotivate: 'Intuition',
    planStageDefine: 'Definition',
    planStageDevelop: 'Development',
    planStageIllustrate: 'Worked example',
    planStageExercise: 'Practice',
    planStageCheck: 'Check',
    knowledgeBoundary: 'Knowledge Boundary',
    lastUpdated: 'Last updated',
    saveSnapshot: 'Save snapshot',
    knowledgeGraphCaption: 'Knowledge map · color = mastery · size = questions',
    knowledgeGraphAccessibility: 'Force-directed knowledge graph',
    knowledgeNodeFallback: (n: number) => `Node ${n}`,
    emptyKnowledgeBoundary: 'Set a topic to build your knowledge map.',
    verifiedCount: (n: number) => `verified x${n}`,
    nodeQuestions: (n: number) => `${n} Qs`,
    go: '→ Go',
    goToNode: 'Jump the chat to this knowledge point',
    confidence: 'Confidence',
    confidenceSet: (n: number) => `Set confidence to ${n}`,
    systemNote: 'System note',
    noSystemNote: 'No system note yet.',
    yourNote: 'Your note',
    notePlaceholder: 'Write anything you want to remember about this topic…',
    snapshotHistory: 'Snapshot history',
    noSnapshotHistory: 'No snapshots yet.',
    /* Shell chrome (baseline: frontend/src/i18n.js sidebar.* / topbar.*). */
    searchChats: 'Search chats',
    recents: 'Recents',
    today: 'Today',
    yesterday: 'Yesterday',
    previous7Days: 'Previous 7 days',
    previous30Days: 'Previous 30 days',
    pinned: 'Pinned',
    newBadge: 'New',
    thinkingEffort: 'Thinking',
    effortMedium: 'Medium',
    findInConversation: 'Find in conversation',
    findPlaceholder: 'Find in conversation…',
    previousMatch: 'Previous match',
    nextMatch: 'Next match',
    closeFind: 'Close find',
    findCount: (current: number, total: number) => `${current}/${total}`,
    shareConversation: 'Share conversation',
    helpful: 'Helpful',
    notHelpful: 'Not helpful',
    reExplain: 'Re-explain from a different angle',
    deleteMessage: 'Delete message',
    /* Baseline chrome (frontend/src/i18n.js sidebar.* / topbar.*). */
    startNewChat: 'Start a new chat',
    closeSidebar: 'Close sidebar',
    openSidebar: 'Open sidebar',
    navLibrary: 'Library',
    navProjects: 'Projects',
    navScheduled: 'Scheduled',
    navPlugins: 'Plugins',
    navSites: 'Sites',
    navMore: 'More',
    navKbd: '⌘K',
    toggleSidebar: 'Toggle sidebar',
    toggleTheme: 'Toggle theme',
    displaySettings: 'Display settings',
    openSettings: 'Open settings',
    openSearch: 'Search chats',
    openProjects: 'Open projects',
    modelSwitcher: 'Model and reasoning',
    archiveSession: 'Archive',
    archiveSessionOf: (title: string) => `Archive ${title}`,
    unarchiveSession: 'Unarchive',
    unarchiveSessionOf: (title: string) => `Restore ${title}`,
    deleteSession: 'Delete',
    deleteSessionOf: (title: string) => `Delete ${title}`,
    confirmDeleteSession: 'Confirm delete',
    confirmDeleteSessionOf: (title: string) => `Confirm delete ${title}`,
    moveToProject: 'Move to project',
    moveToProjectOf: (title: string) => `Move ${title} to project`,
    copyMessage: 'Copy',
    copiedMessage: 'Copied',
    addAttachments: 'Add photos and files',
    sessionActions: 'Session actions',
    sessionActionsOf: (title: string) => `Session actions for ${title}`,
  };
}

export type UiStrings = ReturnType<typeof en>;

const zh: UiStrings = {
  brand: 'Socrates',
  newChat: '新对话',
  newExam: '新考试',
  conversations: '会话',
  untitled: '未命名',
  showArchived: (count: number) => `显示已归档会话 (${count})`,
  hideArchived: '隐藏已归档会话',
  restoreSession: (title: string) => `恢复 ${title}`,
  noArchived: '没有已归档会话。',
  emptyChat: '今天想学点什么？',
  messagePlaceholder: '有问题，随便问',
  sendMessage: '发送',
  stopGenerating: '停止生成',
  attachPhotos: '添加图片',
  attachFile: '添加文件',
  takePhoto: '拍照',
  removeAttachment: (name: string) => `移除 ${name}`,
  startVoiceInput: '开始语音输入',
  stopVoiceInput: '停止语音输入',
  toggleReasoning: '切换思考过程',
  reasoning: '思考过程',
  listenMessage: '朗读',
  listen: '🔊 朗读',
  editMessage: 'Edit message',
  regenerateMessage: 'Regenerate response',
  branchMessage: '从这里分支',
  copyCode: '复制代码',
  copied: '已复制',
  copyFailed: '复制失败',
  code: '代码',
  codeExpand: (n: number) => `展开其余 ${n} 行`,
  codeCollapse: '收起',
  formula: '公式',
  notesTitle: '注释',
  toggleToolDetails: (name: string) => `切换 ${name} 详情`,
  toolFailed: '失败',
  toolCompleted: '已完成',
  toolRunning: '运行中',
  thinking: '…',
  openArtifact: (name: string) => `在作品岛中打开 ${name}`,
  openInIsland: '打开',
  visualization: '可视化',
  artifactSummary: '摘要',
  closeViewer: '关闭预览',
  artifactError: '无法显示该作品。',
  openFile: (name: string) => `打开 ${name}`,
  file: '文件',
  examTitle: '考试',
  examQuestionOf: (n: number, total: number) => `第 ${n} / ${total} 题`,
  examMultipleChoice: '选择题',
  examFillBlank: '填空题',
  examShortAnswer: '简答题',
  examAnswerPlaceholder: '输入你的答案…',
  examSubmit: '交卷',
  examMissingAnswers: '请先完成所有题目再交卷。',
  examAnsweredOf: (n: number, total: number) => `已答 ${n} / ${total}`,
  examScore: (correct: number, total: number, percent: number) => `${correct} / ${total} · ${percent}% 正确`,
  examCorrect: '正确',
  examIncorrect: '错误',
  examExpected: '期望答案',
  examCorrectAnswer: '正确答案',
  examExplanation: '解释',
  examSaved: '已保存',
  modelTitle: '模型',
  chooseModel: '选择模型',
  filterModels: '筛选模型…',
  useModel: (name: string) => `使用 ${name}`,
  manageModels: '管理模型与密钥',
  closeModelPicker: '关闭模型选择器',
  noModels: '暂无模型。',
  noModelMatches: '无匹配。',
  assistantTitle: '助手',
  chooseAssistant: '选择助手',
  filterAssistants: '筛选助手…',
  useAssistant: (name: string) => `使用 ${name}`,
  manageAssistants: '管理助手',
  closeAssistantPicker: '关闭助手选择器',
  noAssistants: '暂无助手。',
  noAssistantMatches: '无匹配。',
  noAssistant: '不使用助手',
  quizCorrect: (answer: string) => `答对了（${answer}）。`,
  quizWrong: (answer: string) => `不太对，正确答案是 ${answer}。`,
  quizRecorded: (letter: string) => `已记录：${letter}。`,
  quizPick: (letter: string, question: string) => `第${letter}项：${question}`,
  showHint: '显示提示',
  hideHint: '隐藏提示',
  revealAnswer: '查看答案',
  submitAnswer: '提交',
  practicePlaceholder: '输入你的答案…',
  practiceEmpty: '请先输入答案。',
  practiceSent: '已发送，等待 AI 点评。',
  practiceSelfCorrect: '答对了！',
  practiceSelfWrong: (answer: string) => `不太对，正确答案是：${answer}`,
  scaffoldFallback: '该内容格式异常，已原样展示',
  diagTitle: '快速诊断',
  diagAnsweredOf: (n: number, total: number) => `已答 ${n} / ${total}`,
  diagOption: (question: string, letter: string) => `第${letter}项：${question}`,
  diagSubmit: '开始学习',
  diagMissing: '请先回答所有问题再继续。',
  newTutor: '新辅导',
  knowledge: '知识图谱',
  mistakes: '错题',
  mistakeBook: '错题本',
  mistakesEmpty: '还没有错题。',
  mistakesEmptyHint: '测验选错和练习答错的题目会收集到这里，供你回看。',
  mistakeTypeQuiz: '测验',
  mistakeTypePractice: '练习',
  teachingPlan: '教学计划',
  planProgress: (done: number, total: number, percent: number) => `${done} / ${total} (${percent}%)`,
  planDepth: (count: number) => `${Math.min(count, 3)}/3`,
  planDepthHint: '深入回答 3 次后进入下一个子主题',
  planDone: '[已完成]',
  planStatusInternalized: '已内化',
  planStatusFuzzy: '模糊',
  planStatusBlank: '空白',
  noTeachingPlan: '完成快速诊断后即可生成教学计划。',
  planStageMotivate: '建立直觉',
  planStageDefine: '精确定义',
  planStageDevelop: '深入推导',
  planStageIllustrate: '应用示例',
  planStageExercise: '动手练习',
  planStageCheck: '阶段检查',
  knowledgeBoundary: '知识边界',
  lastUpdated: '最后更新',
  saveSnapshot: '存档当前版本',
  knowledgeGraphCaption: '知识图谱 · 颜色=掌握度 · 大小=提问数',
  knowledgeGraphAccessibility: '知识点力导向图',
  knowledgeNodeFallback: (n: number) => `知识点 ${n}`,
  emptyKnowledgeBoundary: '设置学习主题后，这里会显示知识地图。',
  verifiedCount: (n: number) => `验证 x${n}`,
  nodeQuestions: (n: number) => `${n} 问`,
  go: '→ 进入',
  goToNode: '把对话跳到这个知识点',
  confidence: '掌握置信度',
  confidenceSet: (n: number) => `将置信度设为 ${n}`,
  systemNote: '系统笔记',
  noSystemNote: '暂无系统笔记。',
  yourNote: '我的笔记',
  notePlaceholder: '写下你对本主题想记住的任何内容...',
  snapshotHistory: '存档历史',
  noSnapshotHistory: '暂无存档。',
  /* Shell chrome (baseline: frontend/src/i18n.js sidebar.* / topbar.*). */
  searchChats: '搜索会话',
  recents: '最近',
  today: '今天',
  yesterday: '昨天',
  previous7Days: '最近 7 天',
  previous30Days: '最近 30 天',
  pinned: '已置顶',
  newBadge: '新',
  thinkingEffort: '思考',
  effortMedium: '中等',
  findInConversation: '在对话中查找',
  findPlaceholder: '在对话中查找…',
  previousMatch: '上一处',
  nextMatch: '下一处',
  closeFind: '关闭查找',
  findCount: (current: number, total: number) => `${current}/${total}`,
  shareConversation: '分享对话',
  helpful: '有帮助',
  notHelpful: '没有帮助',
  reExplain: '换个角度重新解释',
  deleteMessage: '删除消息',
  /* Baseline chrome (frontend/src/i18n.js sidebar.* / topbar.*). */
  startNewChat: '开始新对话',
  closeSidebar: '关闭侧边栏',
  openSidebar: '打开侧边栏',
  navLibrary: '库',
  navProjects: '项目',
  navScheduled: '定时',
  navPlugins: '插件',
  navSites: '站点',
  navMore: '更多',
  navKbd: '⌘K',
  toggleSidebar: '切换侧边栏',
  toggleTheme: '切换主题',
  displaySettings: '显示设置',
  openSettings: '打开设置',
  openSearch: '搜索会话',
  openProjects: '打开项目',
  modelSwitcher: '模型与推理',
  archiveSession: '归档',
  archiveSessionOf: (title: string) => `归档 ${title}`,
  unarchiveSession: '取消归档',
  unarchiveSessionOf: (title: string) => `恢复 ${title}`,
  deleteSession: '删除',
  deleteSessionOf: (title: string) => `删除 ${title}`,
  confirmDeleteSession: '确认删除',
  confirmDeleteSessionOf: (title: string) => `确认删除 ${title}`,
  moveToProject: '移动到项目',
  moveToProjectOf: (title: string) => `移动 ${title} 到项目`,
  copyMessage: '复制',
  copiedMessage: '已复制',
  addAttachments: '添加图片和文件',
  sessionActions: '会话操作',
  sessionActionsOf: (title: string) => `${title} 的会话操作`,
};

export function uiStrings(language: UiLanguage = 'en'): UiStrings {
  return language === 'zh' ? zh : en();
}
