/* Shared UI strings for @socrates/ui (DOM-free). Components take an
 * optional `language` prop (default 'en'); the host app passes its settings
 * language down. Dictionaries live next to the components so labels never
 * drift from the markup that renders them. */

export type UiLanguage = 'en' | 'zh';

function en() {
  return {
    brand: 'Socrates',
    newChat: 'New chat',
    newExam: 'New exam',
    conversations: 'Conversations',
    untitled: 'Untitled',
    showArchived: (count: number) => `Show archived conversations (${count})`,
    hideArchived: 'Hide archived conversations',
    restoreSession: (title: string) => `Restore ${title}`,
    noArchived: 'No archived conversations.',
    emptyChat: 'How can I help you learn today?',
    messagePlaceholder: 'Message Socrates',
    sendMessage: 'Send message',
    stopGenerating: 'Stop generating',
    attachPhotos: 'Attach photos',
    attachFile: 'Attach a file',
    takePhoto: 'Take a photo',
    removeAttachment: (name: string) => `Remove ${name}`,
    startVoiceInput: 'Start voice input',
    stopVoiceInput: 'Stop voice input',
    toggleReasoning: 'Toggle reasoning',
    reasoning: 'Reasoning',
    listenMessage: 'Listen to this message',
    listen: '🔊 Listen',
    copyCode: 'Copy code',
    copied: 'Copied',
    copyFailed: 'Copy failed',
    code: 'Code',
    toggleToolDetails: (name: string) => `Toggle ${name} details`,
    toolFailed: 'Failed',
    toolCompleted: 'Completed',
    toolRunning: 'Running',
    thinking: '…',
    openArtifact: (name: string) => `Open ${name} in the artifact island`,
    openInIsland: 'Open',
    visualization: 'Visualization',
    artifactSummary: 'Summary',
    closeViewer: 'Close preview',
    artifactError: 'This artifact could not be displayed.',
    openFile: (name: string) => `Open ${name}`,
    file: 'File',
    examTitle: 'Exam',
    examQuestionOf: (n: number, total: number) => `Question ${n} / ${total}`,
    examMultipleChoice: 'Multiple choice',
    examFillBlank: 'Fill blank',
    examShortAnswer: 'Short answer',
    examAnswerPlaceholder: 'Type your answer…',
    examSubmit: 'Submit exam',
    examMissingAnswers: 'Answer every question before submitting.',
    examAnsweredOf: (n: number, total: number) => `${n} / ${total} answered`,
    examScore: (correct: number, total: number, percent: number) => `${correct} / ${total} · ${percent}% correct`,
    examCorrect: 'Correct',
    examIncorrect: 'Incorrect',
    examExpected: 'Expected',
    examCorrectAnswer: 'Correct answer',
    examExplanation: 'Explanation',
    examSaved: 'Saved',
  };
}

export type UiStrings = ReturnType<typeof en>;

const zh: UiStrings = {
  brand: 'Socrates',
  newChat: '新对话',
  newExam: '新考试',
  conversations: '会话',
  untitled: '未命名',
  showArchived: (count: number) => `显示已归档会话 (${count})`,
  hideArchived: '隐藏已归档会话',
  restoreSession: (title: string) => `恢复 ${title}`,
  noArchived: '没有已归档会话。',
  emptyChat: '今天想学点什么？',
  messagePlaceholder: '给 Socrates 发消息',
  sendMessage: '发送',
  stopGenerating: '停止生成',
  attachPhotos: '添加图片',
  attachFile: '添加文件',
  takePhoto: '拍照',
  removeAttachment: (name: string) => `移除 ${name}`,
  startVoiceInput: '开始语音输入',
  stopVoiceInput: '停止语音输入',
  toggleReasoning: '切换思考过程',
  reasoning: '思考过程',
  listenMessage: '朗读这条消息',
  listen: '🔊 朗读',
  copyCode: '复制代码',
  copied: '已复制',
  copyFailed: '复制失败',
  code: '代码',
  toggleToolDetails: (name: string) => `切换 ${name} 详情`,
  toolFailed: '失败',
  toolCompleted: '已完成',
  toolRunning: '运行中',
  thinking: '…',
  openArtifact: (name: string) => `在作品岛中打开 ${name}`,
  openInIsland: '打开',
  visualization: '可视化',
  artifactSummary: '摘要',
  closeViewer: '关闭预览',
  artifactError: '无法显示该作品。',
  openFile: (name: string) => `打开 ${name}`,
  file: '文件',
  examTitle: '考试',
  examQuestionOf: (n: number, total: number) => `第 ${n} / ${total} 题`,
  examMultipleChoice: '选择题',
  examFillBlank: '填空题',
  examShortAnswer: '简答题',
  examAnswerPlaceholder: '输入你的答案…',
  examSubmit: '交卷',
  examMissingAnswers: '请先完成所有题目再交卷。',
  examAnsweredOf: (n: number, total: number) => `已答 ${n} / ${total}`,
  examScore: (correct: number, total: number, percent: number) => `${correct} / ${total} · ${percent}% 正确`,
  examCorrect: '正确',
  examIncorrect: '错误',
  examExpected: '期望答案',
  examCorrectAnswer: '正确答案',
  examExplanation: '解释',
  examSaved: '已保存',
};

export function uiStrings(language: UiLanguage = 'en'): UiStrings {
  return language === 'zh' ? zh : en();
}
