import { useSettingsStore } from '@socrates/settings';

/* App-owned screen strings (en/zh). @socrates/ui components carry their own
 * dictionary (packages/ui/src/strings.ts) and take `language` props; these
 * screens read the settings language directly so App.tsx stays a thin shell.
 * Errors surfaced from callbacks resolve the language at call time. */

export type AppLanguage = 'en' | 'zh';

function en() {
  return {
    restoring: 'Restoring session…',
    toggleSidebar: 'Toggle sidebar',
    clearProjectFilter: (name: string) => `Clear project filter ${name}`,
    appTitle: (title: string) => title || 'Socrates',
    openProjects: 'Open projects',
    openSearch: 'Open search',
    openSettings: 'Open settings',
    toggleTheme: 'Toggle theme',
    sessionActions: 'Session actions',
    moveToProject: '📁 Move to project',
    archiveSession: '📦 Archive session',
    deleteSession: '🗑 Delete session',
    confirmDeleteSession: '🗑 Tap again to permanently delete (messages, files, artifacts)',
    moveSessionTo: (title: string) => `Move ${title} to project`,
    archiveSessionOf: (title: string) => `Archive ${title}`,
    deleteSessionOf: (title: string) => `Delete ${title}`,
    confirmDeleteSessionOf: (title: string) => `Confirm delete ${title}`,
    closeSessionMenu: 'Close session menu',
    cancel: 'Cancel',
    guestSendBlocked: 'Sign in to send messages. Guest conversations stay on this device.',
    conversationLoading: 'Conversation is loading. Please try again in a moment.',
    couldNotLoadConversation: 'Could not load conversation',
    couldNotOpenConversation: 'Could not open conversation',
    archiveFailed: 'Archive failed',
    restoreFailed: 'Restore failed',
    deleteFailed: 'Delete failed',
    moveFailed: 'Move failed',
    couldNotLoadUsage: 'Could not load usage',
    signInToOpen: 'Sign in to open this conversation.',
    pickImagesFailed: 'Could not pick images',
    takePhotoFailed: 'Could not take a photo',
    pickFileFailed: 'Could not pick a file',
    prepareAttachmentsFailed: 'Could not prepare attachments',
    speechFailed: 'Speech failed',
    voiceInputFailed: 'Voice input failed',
    stopBeforeArchive: 'Stop the response before archiving this conversation.',
    stopBeforeDelete: 'Stop the response before deleting this conversation.',
    stopBeforeDeleteProject: 'Stop the response before deleting this project.',
    syncFailed: 'Sync failed',
    signInFailed: 'Sign in failed',
    codeSignInFailed: 'Code sign in failed',
    codeSent: 'Code sent — check your email, then enter it above.',
    codeSendFailed: 'Could not send code',
    registered: 'Account created — verify via the emailed link, then sign in.',
    registerFailed: 'Registration failed',
    resent: 'Verification email re-sent — check your inbox.',
    resendFailed: 'Could not re-send email',
    resetSent: 'If the address is registered, a reset link is on its way.',
    resetSendFailed: 'Could not send reset link',
    signInPrompt: 'Socrates',
    signInSub: 'Sign in to sync chats across Web + Android',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    newPasswordLabel: 'Password (8+ characters)',
    newPasswordInput: 'New password',
    loginCodeLabel: 'Login code',
    codePlaceholder: '8-character code',
    signIn: 'Sign in',
    working: 'Working…',
    useCodeInstead: 'Use a login code instead',
    createAccountLink: 'Create a new account',
    forgotPasswordLink: 'Forgot password?',
    backToPassword: 'Back to password sign in',
    backToSignIn: 'Back to sign in',
    emailMeCode: 'Email me a code',
    verifyAndSignIn: 'Verify & sign in',
    createAccount: 'Create account',
    resendVerification: 'Resend verification email',
    registerHint: 'We email a verification link (it opens the website). Come back and sign in afterwards.',
    emailResetLink: 'Email reset link',
    forgotHint: 'The reset link opens the website and expires in 1 hour.',
    continueWithoutLogin: 'Continue without login',
    projectsTitle: 'Projects',
    moveSessionTitle: (title: string) => `Move “${title}” to…`,
    allChats: 'All chats',
    noProjectFilter: 'No project filter',
    unfiled: 'No project (unfiled)',
    unfiledHint: 'Remove the session from its project',
    moveTo: (name: string) => `Move to ${name}`,
    projectLabel: (name: string) => `Project ${name}`,
    loadingProjects: 'Loading projects…',
    retryLoadingProjects: 'Retry loading projects',
    retry: 'Retry',
    newProjectName: 'New project name',
    createProject: 'Create project',
    noProjectsYet: 'No projects yet. Create a project to organize your sessions.',
    renameOf: (name: string) => `Rename ${name}`,
    renameInput: (name: string) => `Rename ${name}`,
    saveNameOf: (name: string) => `Save name for ${name}`,
    cancelRename: 'Cancel rename',
    deleteOf: (name: string) => `Delete ${name}`,
    confirmDeleteOf: (name: string) => `Confirm delete ${name}`,
    cancelDelete: 'Cancel delete',
    deleteProjectWarning: 'Permanently delete this project and its conversations, files and artifacts?',
    operationFailed: 'Operation failed',
    backToChat: 'Back to chat',
    searchHint: 'Type at least 2 characters to search titles, topics and messages.',
    searchPlaceholder: 'Search conversations',
    searching: 'Searching…',
    searchFailed: 'Search failed',
    noResultsFor: (query: string) => `No results for “${query}”.`,
    openConversation: (title: string) => `Open ${title}`,
    openMessageMatch: 'Open message in conversation',
    untitled: 'Untitled',
    conversationKind: 'Conversation',
    messageMatchKind: 'Message match',
    settingsTitle: 'Settings',
    appearance: 'Appearance',
    lightTheme: 'light theme',
    darkTheme: 'dark theme',
    lightLabel: '☀ Light',
    darkLabel: '☾ Dark',
    languageLabel: 'Language',
    enLanguage: 'en language',
    zhLanguage: 'zh language',
    haptics: 'Haptics',
    assistantTone: 'Assistant tone',
    toneOf: (label: string) => `${label} tone`,
    account: 'Account',
    guestAccount: 'Guest',
    guestHint: 'Local only — sign in for sync and usage',
    loadingUsage: 'Loading usage…',
    retryLoadingUsage: 'Retry loading usage',
    conversationsCount: 'Conversations',
    providersCount: 'Providers',
    graphNodesCount: 'Knowledge nodes',
    tokensThisMonth: 'Tokens this month',
    currentPassword: 'Current password',
    newPassword8: 'New password (8+ characters)',
    changePassword: 'Change password',
    changingPassword: 'Changing…',
    passwordChanged: 'Password changed.',
    passwordChangeFailed: 'Password change failed',
    signOut: 'Sign out',
    providersTitle: 'Models & keys',
    providersHint: 'Keys are stored encrypted on the server — this screen only sends them once. Activating one provider deactivates the rest.',
    loadingProviders: 'Loading providers…',
    retryLoadingProviders: 'Retry loading providers',
    builtIn: 'Built-in',
    noKeyStored: 'no key stored',
    activateProvider: (name: string) => `Use ${name}`,
    deleteProvider: (name: string) => `Delete ${name}`,
    confirmDeleteProvider: (name: string) => `Confirm delete ${name}`,
    deleteProviderWarning: 'Delete this provider and its stored key?',
    deleteConfirm: 'Delete?',
    providerLabel: 'Label',
    providerLabelHint: 'Custom (optional)',
    providerUrl: 'API base URL (https)',
    providerModel: 'Model id',
    providerKey: 'API key',
    providerVision: 'Vision (image input)',
    addProvider: 'Add provider',
    openProviders: 'Models & keys',
  };
}

export type AppStrings = ReturnType<typeof en>;

const zh: AppStrings = {
  restoring: '正在恢复会话…',
  toggleSidebar: '切换侧边栏',
  clearProjectFilter: (name: string) => `清除项目筛选 ${name}`,
  appTitle: (title: string) => title || 'Socrates',
  openProjects: '打开项目',
  openSearch: '打开搜索',
  openSettings: '打开设置',
  toggleTheme: '切换主题',
  sessionActions: '会话操作',
  moveToProject: '📁 移到项目',
  archiveSession: '📦 归档会话',
  deleteSession: '🗑 删除会话',
  confirmDeleteSession: '🗑 再点一次彻底删除（含消息、文件、作品）',
  moveSessionTo: (title: string) => `将 ${title} 移到项目`,
  archiveSessionOf: (title: string) => `归档 ${title}`,
  deleteSessionOf: (title: string) => `删除 ${title}`,
  confirmDeleteSessionOf: (title: string) => `确认删除 ${title}`,
  closeSessionMenu: '关闭会话菜单',
  cancel: '取消',
  guestSendBlocked: '请先登录再发送消息。访客会话仅保存在本机。',
  conversationLoading: '会话正在加载，请稍后再试。',
  couldNotLoadConversation: '无法加载会话',
  couldNotOpenConversation: '无法打开会话',
    archiveFailed: '归档失败',
    restoreFailed: '恢复失败',
    deleteFailed: '删除失败',
    moveFailed: '移动失败',
    couldNotLoadUsage: '无法加载用量',
    signInToOpen: '请先登录再打开此会话。',
    pickImagesFailed: '无法选择图片',
    takePhotoFailed: '无法拍照',
    pickFileFailed: '无法选择文件',
    prepareAttachmentsFailed: '无法准备附件',
    speechFailed: '朗读失败',
    voiceInputFailed: '语音输入失败',
  stopBeforeArchive: '请先停止回复再归档此会话。',
  stopBeforeDelete: '请先停止回复再删除此会话。',
  stopBeforeDeleteProject: '请先停止回复再删除此项目。',
  syncFailed: '同步失败',
  signInFailed: '登录失败',
  codeSignInFailed: '验证码登录失败',
  codeSent: '验证码已发送——查收邮件后在上方输入。',
  codeSendFailed: '验证码发送失败',
  registered: '账户已创建——通过邮件链接验证后回来登录。',
  registerFailed: '注册失败',
  resent: '验证邮件已重发——请查收。',
  resendFailed: '重发失败',
  resetSent: '如果该邮箱已注册，重置链接正在路上。',
  resetSendFailed: '重置链接发送失败',
  signInPrompt: 'Socrates',
  signInSub: '登录以在网页 + 安卓间同步聊天',
  emailLabel: '邮箱',
  passwordLabel: '密码',
  newPasswordLabel: '密码（8 位以上）',
  newPasswordInput: '新密码',
    loginCodeLabel: '登录验证码',
    codePlaceholder: '8 位验证码',
    signIn: '登录',
    working: '处理中…',
  useCodeInstead: '改用登录验证码',
  createAccountLink: '创建新账户',
  forgotPasswordLink: '忘记密码？',
  backToPassword: '返回密码登录',
  backToSignIn: '返回登录',
  emailMeCode: '发送验证码到邮箱',
  verifyAndSignIn: '验证并登录',
  createAccount: '创建账户',
  resendVerification: '重发验证邮件',
  registerHint: '我们会发送验证链接（在网页中打开），之后回来登录即可。',
  emailResetLink: '发送重置链接',
  forgotHint: '重置链接在网页中打开，1 小时内有效。',
  continueWithoutLogin: '不登录继续',
  projectsTitle: '项目',
  moveSessionTitle: (title: string) => `将“${title}”移到…`,
  allChats: '全部聊天',
  noProjectFilter: '无项目筛选',
  unfiled: '无项目（未归类）',
  unfiledHint: '将此会话移出其项目',
  moveTo: (name: string) => `移到 ${name}`,
  projectLabel: (name: string) => `项目 ${name}`,
  loadingProjects: '正在加载项目…',
    retryLoadingProjects: '重试加载项目',
    retry: '重试',
  newProjectName: '新项目名称',
  createProject: '创建项目',
  noProjectsYet: '还没有项目。创建一个项目来组织你的会话。',
  renameOf: (name: string) => `重命名 ${name}`,
  renameInput: (name: string) => `重命名 ${name}`,
  saveNameOf: (name: string) => `保存 ${name} 的名称`,
  cancelRename: '取消重命名',
  deleteOf: (name: string) => `删除 ${name}`,
  confirmDeleteOf: (name: string) => `确认删除 ${name}`,
  cancelDelete: '取消删除',
  deleteProjectWarning: '彻底删除此项目及其会话、文件和作品？',
  operationFailed: '操作失败',
  backToChat: '返回聊天',
  searchHint: '输入至少 2 个字符搜索标题、话题和消息。',
  searchPlaceholder: '搜索会话',
  searching: '搜索中…',
  searchFailed: '搜索失败',
  noResultsFor: (query: string) => `没有“${query}”的结果。`,
  openConversation: (title: string) => `打开 ${title}`,
    openMessageMatch: '打开消息所在会话',
    untitled: '未命名',
  conversationKind: '会话',
  messageMatchKind: '消息匹配',
  settingsTitle: '设置',
  appearance: '外观',
  lightTheme: '浅色主题',
  darkTheme: '深色主题',
  lightLabel: '☀ 浅色',
  darkLabel: '☾ 深色',
  languageLabel: '语言',
  enLanguage: '英文',
  zhLanguage: '中文',
  haptics: '触感反馈',
  assistantTone: '助手语气',
  toneOf: (label: string) => `${label}语气`,
  account: '账户',
  guestAccount: '访客',
  guestHint: '仅本地——登录后可同步并查看用量',
  loadingUsage: '正在加载用量…',
  retryLoadingUsage: '重试加载用量',
  conversationsCount: '会话数',
  providersCount: '模型供应商数',
  graphNodesCount: '知识节点',
  tokensThisMonth: '本月 token',
  currentPassword: '当前密码',
  newPassword8: '新密码（8 位以上）',
  changePassword: '修改密码',
  changingPassword: '修改中…',
  passwordChanged: '密码已修改。',
  passwordChangeFailed: '密码修改失败',
    signOut: '退出登录',
    providersTitle: '模型与密钥',
    providersHint: '密钥在服务端加密存储——本屏只发送一次。启用一个供应商会停用其余。',
    loadingProviders: '正在加载供应商…',
    retryLoadingProviders: '重试加载供应商',
    builtIn: '内置',
    noKeyStored: '未存密钥',
    activateProvider: (name: string) => `使用 ${name}`,
    deleteProvider: (name: string) => `删除 ${name}`,
    confirmDeleteProvider: (name: string) => `确认删除 ${name}`,
    deleteProviderWarning: '删除此供应商及其存储的密钥？',
    deleteConfirm: '删除？',
    providerLabel: '名称',
    providerLabelHint: '自定义（可选）',
    providerUrl: 'API 地址（https）',
    providerModel: '模型 id',
    providerKey: 'API 密钥',
    providerVision: '视觉（图片输入）',
    addProvider: '添加供应商',
    openProviders: '模型与密钥',
};

export function appStrings(language: AppLanguage = 'en'): AppStrings {
  return language === 'zh' ? zh : en();
}

/** Hook for app-owned screens; re-renders with the settings language. */
export function useAppStrings(): AppStrings {
  const language = useSettingsStore((s) => s.language);
  return appStrings(language);
}

/** Error/notice lookup for callbacks outside React render. */
export function appStringsNow(): AppStrings {
  return appStrings(useSettingsStore.getState().language);
}
