/* Frozen provider auth snapshot for OOMOL-cloud mode — EDIT WITH CARE.
 *
 * This was originally generated by scripts/gen-oc-cloud-auth.mjs from the
 * vendored open-connector/ tree, which has since been removed: Socrates now
 * reaches every provider through the OOMOL-hosted runtime (@oomol-lab/
 * connector), so there is no local sidecar and no tree to regenerate from.
 * Treat the map below as hand-maintained data keyed by ocService; add or
 * adjust an entry to match a provider's auth metadata on the OOMOL gateway.
 */

export interface CloudAuthField {
  key: string;
  label?: string;
  inputType?: string;
  secret?: boolean;
  required?: boolean;
  placeholder?: string;
  description?: string;
}

export interface CloudAuthConfig {
  type: string;
  label?: string;
  placeholder?: string;
  description?: string;
  fields?: CloudAuthField[];
}

export interface CloudAuthMeta {
  authTypes: string[];
  auth: CloudAuthConfig[];
  categories: string[];
  actionCount: number;
}

/** Auth metadata per ocService (stable ids, no runtime open-connector import). */
export const OPEN_CONNECTOR_CLOUD_AUTH: Record<string, CloudAuthMeta> = {
  "7_shifts": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "Access Token",
        "placeholder": "7SHIFTS_ACCESS_TOKEN",
        "description": "7shifts long-lived access token sent with the Authorization: Bearer header. Create or view access tokens in Company Settings > Developer Tools, as described in the 7shifts authentication docs: https://developers.7shifts.com/reference/authentication."
      }
    ],
    "categories": [
      "Productivity"
    ],
    "actionCount": 7
  },
  "accredible_certificates": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "ACCREDIBLE_API_KEY",
        "description": "Accredible API key sent in the Authorization header as Token token=<API key>. Create or view API keys from API Management in Accredible: https://help.accredible.com/s/article/how-do-i-find-my-integration-api-key."
      }
    ],
    "categories": [
      "Productivity",
      "Data"
    ],
    "actionCount": 8
  },
  "acculynx": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "AccuLynx API key",
        "description": "AccuLynx API key used with the Authorization Bearer header. Create or view your key on the official AccuLynx API Keys page: https://my.acculynx.com/apikeys"
      }
    ],
    "categories": [
      "Productivity",
      "Marketing"
    ],
    "actionCount": 12
  },
  "affinda": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "AFFINDA_API_KEY",
        "description": "Affinda API key sent as a Bearer token. Create and rotate keys from your Affinda user settings: https://docs.affinda.com/reference/authentication."
      }
    ],
    "categories": [
      "AI",
      "Data"
    ],
    "actionCount": 6
  },
  "affinity": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "affinity_api_key",
        "description": "Affinity API key used with the Authorization Bearer header. Create it in Settings -> Manage Apps -> API Keys."
      }
    ],
    "categories": [
      "Productivity",
      "Data"
    ],
    "actionCount": 20
  },
  "agent_mail": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "am_...",
        "description": "AgentMail API key used with the Authorization Bearer header. Create it in the AgentMail Console API Keys section."
      }
    ],
    "categories": [
      "Communication",
      "Productivity"
    ],
    "actionCount": 102
  },
  "agentql": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "AGENTQL_API_KEY",
        "description": "AgentQL API key used with the X-API-Key header. Get it from the AgentQL developer dashboard."
      }
    ],
    "categories": [
      "AI",
      "Developer Tools",
      "Data"
    ],
    "actionCount": 4
  },
  "agenty": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "agenty_api_key",
        "description": "Agenty API key used with the X-Agenty-ApiKey header. Manage it from Agenty API Keys docs: https://agenty.com/docs/api-keys/88."
      }
    ],
    "categories": [
      "Developer Tools",
      "Data"
    ],
    "actionCount": 31
  },
  "agiled": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Token",
        "placeholder": "AGILED_API_TOKEN",
        "description": "Agiled API token sent as the api_token query parameter. Create or view it in Settings > API Settings in your Agiled account: https://my.agiled.app/developers."
      }
    ],
    "categories": [
      "Productivity",
      "Data"
    ],
    "actionCount": 15
  },
  "agora": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "Customer Secret",
        "placeholder": "AGORA_CUSTOMER_SECRET",
        "description": "Agora Customer Secret used as the Basic Auth password. View Customer ID and Customer Secret in the Agora Console RESTful API settings: https://console.agora.io/v2."
      }
    ],
    "categories": [
      "Communication",
      "Developer Tools"
    ],
    "actionCount": 7
  },
  "airbrake": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "User API Key",
        "placeholder": "AIRBRAKE_USER_API_KEY",
        "description": "Airbrake User API key sent as the key query parameter. Airbrake documents User API keys for accessing project data: https://docs.airbrake.io/docs/devops-tools/api/#authentication"
      }
    ],
    "categories": [
      "Developer Tools",
      "Data"
    ],
    "actionCount": 8
  },
  "aircall": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Token",
        "placeholder": "AIRCALL_API_TOKEN",
        "description": "Aircall API token used as the Basic Auth password. Generate or view API credentials in Aircall Dashboard integrations: https://dashboard.aircall.io/integrations/api."
      }
    ],
    "categories": [
      "Communication",
      "Productivity"
    ],
    "actionCount": 10
  },
  "airtable": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "Personal Access Token",
        "placeholder": "patXXXXXXXXXXXXXX",
        "description": "Airtable personal access token used with the Authorization Bearer header. Create it in the Airtable developer hub at https://airtable.com/create/tokens."
      }
    ],
    "categories": [
      "Productivity",
      "Data"
    ],
    "actionCount": 14
  },
  "aivoov": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "aivoov_api_key",
        "description": "AiVOOV API key sent with the x-api-key header. Get it from your AiVOOV account while setting up the Text-to-Speech API: https://aivoov.com/text-to-speech-api."
      }
    ],
    "categories": [
      "AI",
      "Design & Media"
    ],
    "actionCount": 2
  },
  "alt_text_ai": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "ALT_TEXT_AI_API_KEY",
        "description": "AltText.ai API key sent with the X-API-Key header. Create or view API keys in your AltText.ai account: https://alttext.ai/account/api_keys."
      }
    ],
    "categories": [
      "AI",
      "Design & Media"
    ],
    "actionCount": 7
  },
  "amap": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "amap_api_key",
        "description": "AMap API key sent as the key query parameter. Create it in the AMap Open Platform console: https://lbs.amap.com/api/webservice/guide/create-project/get-key ."
      }
    ],
    "categories": [
      "Location"
    ],
    "actionCount": 15
  },
  "anchor_browser": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "anchor_api_key",
        "description": "Anchor Browser API key sent in the anchor-api-key header. Create or manage API keys in Anchor project settings: https://app.anchorbrowser.io/"
      }
    ],
    "categories": [
      "Developer Tools",
      "AI"
    ],
    "actionCount": 3
  },
  "anthropic": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "anthropic_api_key",
        "description": "Anthropic API key used with the x-api-key header. Create or manage API keys in the Anthropic Console: https://console.anthropic.com/settings/keys."
      }
    ],
    "categories": [
      "AI"
    ],
    "actionCount": 4
  },
  "anthropic_admin": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "Admin API Key",
        "placeholder": "ANTHROPIC_ADMIN_KEY",
        "description": "Anthropic Admin API key sent with the x-api-key header. Create or manage Admin keys in the Anthropic Console: https://console.anthropic.com/settings/admin-keys."
      }
    ],
    "categories": [
      "AI"
    ],
    "actionCount": 6
  },
  "anysearch": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "Enter your AnySearch API key",
        "description": "AnySearch API key sent as a Bearer token. Create and manage keys in the AnySearch console: https://www.anysearch.com/console/api-keys."
      }
    ],
    "categories": [
      "AI",
      "Data"
    ],
    "actionCount": 4
  },
  "apipie_ai": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "description": "APIpie AI API key used with the Authorization Bearer header. Create or manage keys at https://apipie.ai/profile/api-keys."
      }
    ],
    "categories": [
      "AI",
      "Developer Tools"
    ],
    "actionCount": 4
  },
  "asana": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "Personal Access Token",
        "placeholder": "asana_pat",
        "description": "Asana personal access token used with the Authorization Bearer header. Get it from the Asana developer console at https://app.asana.com/0/my-apps."
      }
    ],
    "categories": [
      "Productivity"
    ],
    "actionCount": 10
  },
  "assemblyai": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "ASSEMBLYAI_API_KEY",
        "description": "AssemblyAI API key sent in the Authorization header. Create or manage API keys in the AssemblyAI Dashboard: https://www.assemblyai.com/dashboard."
      }
    ],
    "categories": [
      "AI",
      "Developer Tools"
    ],
    "actionCount": 6
  },
  "atlas_so": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "atlas_api_key",
        "description": "Atlas.so API key sent as an Authorization Bearer token. Find it in Atlas under App Config > API: https://app.getatlas.io/configuration/external-api."
      }
    ],
    "categories": [
      "Communication",
      "Productivity"
    ],
    "actionCount": 10
  },
  "baidu_maps": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "AK (Access Key)",
        "placeholder": "Baidu Maps AK",
        "description": "Baidu Maps AK passed via the ak query parameter. Create or manage keys in the official console: https://lbsyun.baidu.com/apiconsole/key. Provide an SK in the optional field when your application requires SN validation."
      }
    ],
    "categories": [
      "Location"
    ],
    "actionCount": 14
  },
  "bark": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "Device Key",
        "placeholder": "device key or https://api.day.app/{device_key}",
        "description": "Bark device key used as the device_key field for push requests. Open the Bark iOS app and copy the push URL shown in the tutorial, then paste either the key or full URL: https://bark.day.app/#/tutorial."
      }
    ],
    "categories": [
      "Communication"
    ],
    "actionCount": 4
  },
  "beamer": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "BEAMER_API_KEY",
        "description": "Beamer API key sent in the Beamer-Api-Key header. Find or manage it in Settings > API after signing in: https://app.getbeamer.com/settings."
      }
    ],
    "categories": [
      "Communication",
      "Productivity"
    ],
    "actionCount": 4
  },
  "bird": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "Access Key",
        "placeholder": "BIRD_ACCESS_KEY",
        "description": "Bird access key used in the Authorization header for API requests. Create and manage access keys in Bird security settings: https://app.bird.com/settings/security/access-keys"
      }
    ],
    "categories": [
      "Communication",
      "Marketing"
    ],
    "actionCount": 12
  },
  "bluesky": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "App Password",
        "placeholder": "xxxx-xxxx-xxxx-xxxx",
        "description": "Bluesky app password used to create an AT Protocol session. Create an app password in Bluesky Settings > Privacy and Security > App Passwords: https://bsky.app/settings/app-passwords"
      }
    ],
    "categories": [
      "Social",
      "Communication"
    ],
    "actionCount": 3
  },
  "botpress": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Token",
        "placeholder": "BOTPRESS_API_TOKEN",
        "description": "Botpress API token sent as a Bearer token. Generate a token from the Botpress dashboard API settings and use it with your workspace ID: https://botpress.com/docs/api-reference/admin-api/getting-started."
      }
    ],
    "categories": [
      "AI",
      "Developer Tools"
    ],
    "actionCount": 3
  },
  "botsonic": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "Bot API Token",
        "placeholder": "botsonic_bot_api_token",
        "description": "Botsonic bot API token sent with the X-BOT-KEY header. Open your Botsonic dashboard, select a bot, then copy the token from Integration Page > REST API as described at https://docs.botsonic.com/docs/rest-api."
      }
    ],
    "categories": [
      "AI",
      "Communication"
    ],
    "actionCount": 4
  },
  "browse_ai": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "YOUR_SECRET_API_KEY",
        "description": "Browse AI secret API key passed in the Authorization Bearer header. Create it in the API tab of your Browse AI dashboard: https://help.browse.ai/en/articles/12683249-api-guide-getting-started."
      }
    ],
    "categories": [
      "Data",
      "Developer Tools"
    ],
    "actionCount": 6
  },
  "callerapi": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "CALLERAPI_API_KEY",
        "description": "CallerAPI key sent with the x-auth header. Get it from the CallerAPI dashboard: https://callerapi.com/dashboard"
      }
    ],
    "categories": [
      "Communication",
      "Security"
    ],
    "actionCount": 2
  },
  "callingly": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "Bearer Token",
        "placeholder": "CALLINGLY_BEARER_TOKEN",
        "description": "Callingly bearer token used with the Authorization header. Create it under Settings > API Keys in the Callingly dashboard: https://callingly.com/dashboard/settings/api_keys"
      }
    ],
    "categories": [
      "Communication",
      "Productivity"
    ],
    "actionCount": 12
  },
  "callpage": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Token",
        "placeholder": "CALLPAGE_API_TOKEN",
        "description": "CallPage API token sent with the Authorization header. Generate or view it in the CallPage dashboard API settings: https://core.callpage.io/settings/api"
      }
    ],
    "categories": [
      "Communication",
      "Productivity"
    ],
    "actionCount": 7
  },
  "campaign_cleaner": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "cc_live_xxxxxxxxxxxxx",
        "description": "Campaign Cleaner API key sent in the X-CC-API-Key header. Manage API keys from API Management in the Campaign Cleaner dashboard."
      }
    ],
    "categories": [
      "Communication",
      "Marketing"
    ],
    "actionCount": 7
  },
  "chatbotkit": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "chatbotkit_api_key",
        "description": "ChatBotKit API key used with the Authorization Bearer header. Generate it from your ChatBotKit account tokens page: https://chatbotkit.com/tokens."
      }
    ],
    "categories": [
      "AI",
      "Developer Tools"
    ],
    "actionCount": 27
  },
  "chatpdf": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "sec_...",
        "description": "ChatPDF API key sent in the x-api-key header. View your key in the ChatPDF backend API documentation after signing in: https://www.chatpdf.com/docs/api/backend."
      }
    ],
    "categories": [
      "AI",
      "Productivity"
    ],
    "actionCount": 3
  },
  "chatwork": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Token",
        "placeholder": "chatwork_api_token",
        "description": "Chatwork API token sent with the X-ChatWorkToken header. Generate it from the Chatwork API settings page."
      }
    ],
    "categories": [
      "Communication",
      "Productivity"
    ],
    "actionCount": 15
  },
  "chorus": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Token",
        "placeholder": "abcdefghijklmnopqrstuvwxyz0123456789",
        "description": "Chorus API token sent as the raw Authorization header value. Generate it from Personal Settings in the Chorus application after your role has API access."
      }
    ],
    "categories": [
      "Communication",
      "Data"
    ],
    "actionCount": 6
  },
  "circle": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Token",
        "placeholder": "CIRCLE_API_TOKEN",
        "description": "Circle Admin API token used with the Authorization Bearer header."
      }
    ],
    "categories": [
      "Communication",
      "Productivity"
    ],
    "actionCount": 8
  },
  "claid_ai": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "CLAID_API_KEY",
        "description": "Claid API key used with the Authorization Bearer header. Create or manage it from the Claid API Keys page: https://claid.ai/account/api"
      }
    ],
    "categories": [
      "AI",
      "Design & Media"
    ],
    "actionCount": 3
  },
  "clickmeeting": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "CLICKMEETING_API_KEY",
        "description": "ClickMeeting API key sent in the X-Api-Key header. Generate or view it in ClickMeeting account settings: https://account-panel.clickmeeting.com/account/details#api."
      }
    ],
    "categories": [
      "Communication",
      "Marketing"
    ],
    "actionCount": 19
  },
  "clicksend": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "CLICKSEND_API_KEY",
        "description": "ClickSend API key used as the Basic Auth password. Find or create it in the ClickSend Dashboard under Credentials: https://dashboard.clicksend.com/#/account/subaccount."
      }
    ],
    "categories": [
      "Communication",
      "Marketing"
    ],
    "actionCount": 13
  },
  "clickup": {
    "authTypes": [
      "oauth2",
      "api_key"
    ],
    "auth": [
      {
        "type": "oauth2"
      },
      {
        "type": "api_key",
        "label": "Personal API Token",
        "placeholder": "clickup_personal_token",
        "description": "ClickUp personal API token sent with the Authorization header. Generate it from Settings > Apps, or see https://developer.clickup.com/docs."
      }
    ],
    "categories": [
      "Productivity"
    ],
    "actionCount": 68
  },
  "cloudflare_email_routing": {
    "authTypes": [
      "custom_credential"
    ],
    "auth": [
      {
        "type": "custom_credential",
        "fields": [
          {
            "key": "email",
            "label": "Cloudflare Account Email",
            "inputType": "text",
            "secret": false,
            "required": false,
            "placeholder": "you@example.com",
            "description": "Email address for legacy Global API Key authentication. Leave blank when using a cfut_ User API Token with Email Routing permissions."
          },
          {
            "key": "apiKey",
            "label": "Cloudflare API Credential",
            "inputType": "password",
            "secret": true,
            "required": true,
            "placeholder": "cloudflare_global_api_key",
            "description": "Use a cfut_ User API Token with Email Routing Rules/Addresses permissions, or a Global API Key (cfk_ or legacy format) with the account email. Cloudflare cfat_ Account API Tokens are not accepted by the Email Routing API: https://developers.cloudflare.com/fundamentals/api/reference/permissions/."
          },
          {
            "key": "accountId",
            "label": "Cloudflare Account ID",
            "inputType": "text",
            "secret": false,
            "required": true,
            "placeholder": "32-character Cloudflare account ID",
            "description": "Default account ID for destination addresses and account rule listings. Action inputs may override it."
          },
          {
            "key": "zoneId",
            "label": "Cloudflare Zone ID",
            "inputType": "text",
            "secret": false,
            "required": true,
            "placeholder": "32-character Cloudflare zone ID",
            "description": "Default zone ID for routing rule actions. Action inputs may override it."
          }
        ]
      }
    ],
    "categories": [
      "Communication",
      "Developer Tools"
    ],
    "actionCount": 5
  },
  "codegen": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Token",
        "placeholder": "CODEGEN_API_TOKEN",
        "description": "Codegen API token sent as a Bearer token. Generate it from the Codegen developer settings page: https://codegen.com/token."
      }
    ],
    "categories": [
      "Developer Tools",
      "AI"
    ],
    "actionCount": 6
  },
  "cohere": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "cohere_api_key",
        "description": "Cohere API key used with the Authorization Bearer header. Create or copy one from https://dashboard.cohere.com/api-keys."
      }
    ],
    "categories": [
      "AI"
    ],
    "actionCount": 3
  },
  "context7": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "ctx7sk-...",
        "description": "Context7 API key sent as a Bearer token. Create and manage keys in the Context7 dashboard: https://context7.com/dashboard."
      }
    ],
    "categories": [
      "Developer Tools",
      "AI"
    ],
    "actionCount": 2
  },
  "courier": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "COURIER_API_KEY",
        "description": "Courier API key used with the Authorization Bearer header. Create or manage keys in the Courier dashboard API Keys page: https://app.courier.com/settings/api-keys."
      }
    ],
    "categories": [
      "Communication",
      "Marketing"
    ],
    "actionCount": 11
  },
  "crisp": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "Token Key",
        "placeholder": "CRISP_TOKEN_KEY",
        "description": "Crisp token key used as the Basic Auth password. For website tokens, generate the key in Crisp Dashboard > Settings > Workspace Settings > Advanced configuration > API Token: https://app.crisp.chat/"
      }
    ],
    "categories": [
      "Communication",
      "Marketing"
    ],
    "actionCount": 5
  },
  "cursor": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "crsr_...",
        "description": "Cursor API key sent with Basic authentication. Create or copy a key from Cursor Dashboard > API Keys: https://cursor.com/dashboard/api"
      }
    ],
    "categories": [
      "Developer Tools",
      "AI"
    ],
    "actionCount": 4
  },
  "customgpt": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "CUSTOMGPT_API_KEY",
        "description": "CustomGPT API key sent as an Authorization Bearer token. Create it in the CustomGPT profile API tab: https://app.customgpt.ai/profile#api."
      }
    ],
    "categories": [
      "AI",
      "Productivity"
    ],
    "actionCount": 7
  },
  "dailybot": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "dailybot_api_key",
        "description": "Dailybot API key sent with the X-API-KEY header. Create or revoke it in the Dailybot integrations dashboard."
      }
    ],
    "categories": [
      "Communication",
      "Productivity"
    ],
    "actionCount": 10
  },
  "data247": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "DATA247_API_KEY",
        "description": "Data247 v3 API key sent with the key query parameter. The Data247 API manual describes API key usage: https://www.data247.com/api_user_manual"
      }
    ],
    "categories": [
      "Data",
      "Communication",
      "Marketing"
    ],
    "actionCount": 5
  },
  "deck_co": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "Secret Key",
        "placeholder": "sk_live_...",
        "description": "Deck.co v2 secret key sent as a Bearer token. Create or view API keys from the Deck.co dashboard API keys page: https://app.deck.co/api-keys."
      }
    ],
    "categories": [
      "AI",
      "Developer Tools"
    ],
    "actionCount": 6
  },
  "deepgram": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "DEEPGRAM_API_KEY",
        "description": "Deepgram API key sent as Authorization: Token <API_KEY>. Create or manage keys in the Deepgram Console and API key guide: https://developers.deepgram.com/docs/create-additional-api-keys."
      }
    ],
    "categories": [
      "AI",
      "Developer Tools"
    ],
    "actionCount": 8
  },
  "deepl": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "DEEPL_API_KEY",
        "description": "DeepL API key sent with the DeepL-Auth-Key authorization scheme. Find and manage it in the API Keys & Limits tab of your DeepL API account: https://developers.deepl.com/docs/getting-started/managing-api-keys."
      }
    ],
    "categories": [
      "AI",
      "Productivity"
    ],
    "actionCount": 3
  },
  "deepseek": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "sk-...",
        "description": "DeepSeek API key used for DeepSeek API requests. Create or manage keys at https://platform.deepseek.com/api_keys."
      }
    ],
    "categories": [
      "AI"
    ],
    "actionCount": 4
  },
  "detect_language": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "DETECT_LANGUAGE_API_KEY",
        "description": "Detect Language uses this API key in the Authorization bearer header. Sign up and get the key from your Detect Language account: https://detectlanguage.com/users/sign_up."
      }
    ],
    "categories": [
      "AI",
      "Data"
    ],
    "actionCount": 4
  },
  "devin": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "Service User API Key",
        "placeholder": "cog_xxxxxxxxxx",
        "description": "Devin service user API key sent in the Authorization Bearer header. Create a service user and generate its API key from Devin Settings > Service users: https://docs.devin.ai/api-reference/authentication."
      }
    ],
    "categories": [
      "AI",
      "Developer Tools"
    ],
    "actionCount": 6
  },
  "diffbot": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Token",
        "placeholder": "DIFFBOT_TOKEN",
        "description": "Diffbot API token sent with the token query parameter. Copy it from the account menu in the Diffbot app."
      }
    ],
    "categories": [
      "Data",
      "AI"
    ],
    "actionCount": 1
  },
  "dingtalk_bot": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "Webhook Access Token",
        "placeholder": "access_token from DingTalk webhook URL",
        "description": "Paste the access_token query value from the DingTalk webhook URL. The full DingTalk custom bot webhook URL is also accepted."
      }
    ],
    "categories": [
      "Communication"
    ],
    "actionCount": 5
  },
  "discord": {
    "authTypes": [
      "oauth2"
    ],
    "auth": [
      {
        "type": "oauth2"
      }
    ],
    "categories": [
      "Communication",
      "Social"
    ],
    "actionCount": 19
  },
  "discordbot": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "Bot Token",
        "placeholder": "Discord bot token",
        "description": "Discord bot token sent as Authorization: Bot <token>. Create a bot in the Discord Developer Portal and invite it to the guilds you want to manage."
      }
    ],
    "categories": [
      "Communication",
      "Developer Tools"
    ],
    "actionCount": 15
  },
  "discourse": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "DISCOURSE_API_KEY",
        "description": "Discourse API key sent with the Api-Key header. Create an API key from your forum admin panel."
      }
    ],
    "categories": [
      "Communication",
      "Productivity"
    ],
    "actionCount": 7
  },
  "dixa": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Token",
        "placeholder": "dixa_api_token",
        "description": "Dixa API token sent with the Authorization header. Administrators can create it in Dixa under Settings > Manage > Integrations > API Tokens: https://docs.dixa.io/docs/tutorial-create-an-api-token."
      }
    ],
    "categories": [
      "Communication",
      "Productivity"
    ],
    "actionCount": 7
  },
  "docsbot_ai": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "DOCSBOT_API_KEY",
        "description": "DocsBot AI user API key sent as a Bearer token. Create or change it from the API Keys section of your DocsBot dashboard: https://docsbot.ai/app/api"
      }
    ],
    "categories": [
      "AI",
      "Data"
    ],
    "actionCount": 6
  },
  "docsumo": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "DOCSUMO_API_KEY",
        "description": "Docsumo API key sent with the apikey header. Copy it from Docsumo API settings."
      }
    ],
    "categories": [
      "AI",
      "Productivity",
      "Data"
    ],
    "actionCount": 6
  },
  "e2b": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "E2B_API_KEY",
        "description": "E2B API key used with the X-API-Key header. Create or view keys in the E2B dashboard: https://e2b.dev/dashboard?tab=keys."
      }
    ],
    "categories": [
      "AI",
      "Developer Tools"
    ],
    "actionCount": 4
  },
  "eagle_doc": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "EAGLE_DOC_API_KEY",
        "description": "Eagle Doc API key sent with the api-key header. Subscribe and sign in to the Eagle Doc API dashboard to copy it."
      }
    ],
    "categories": [
      "AI",
      "Finance",
      "Productivity"
    ],
    "actionCount": 5
  },
  "edenai": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "description": "Eden AI API key used with the Authorization Bearer header. Create or manage keys in your Eden AI account at https://app.edenai.run/settings/api-keys."
      }
    ],
    "categories": [
      "AI",
      "Developer Tools"
    ],
    "actionCount": 2
  },
  "elevenlabs": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "xi-api-key",
        "description": "ElevenLabs API key sent with the xi-api-key header. Create or manage keys from Developers > API Keys."
      }
    ],
    "categories": [
      "AI",
      "Design & Media"
    ],
    "actionCount": 14
  },
  "elevenreader": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "xi-api-key",
        "description": "ElevenLabs API key sent with the xi-api-key header for ElevenReader actions. Create or manage keys from Developers > API Keys."
      }
    ],
    "categories": [
      "AI",
      "Design & Media"
    ],
    "actionCount": 5
  },
  "emailable": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "EMAILABLE_API_KEY",
        "description": "Emailable API key sent with the Authorization Bearer header. Create or roll it from your Emailable dashboard API settings: https://emailable.com/docs/api."
      }
    ],
    "categories": [
      "Communication",
      "Developer Tools"
    ],
    "actionCount": 4
  },
  "emaillistverify": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "EMAILLISTVERIFY_API_KEY",
        "description": "EmailListVerify API key passed as the secret query parameter. Get or activate your API key from the API page: https://emaillistverify.com/api."
      }
    ],
    "categories": [
      "Communication",
      "Marketing"
    ],
    "actionCount": 8
  },
  "emailoctopus": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "00000000-0000-0000-0000-000000000000",
        "description": "EmailOctopus API key used by the official v1 API. Create or manage it from the API key screen in your EmailOctopus account: https://help.emailoctopus.com/article/165-how-to-create-and-delete-api-keys"
      }
    ],
    "categories": [
      "Communication",
      "Marketing"
    ],
    "actionCount": 9
  },
  "encharge": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "ENCHARGE_API_KEY",
        "description": "Encharge API key used with the X-Encharge-Token header. Get it from your Encharge account page: https://app.encharge.io/account/info."
      }
    ],
    "categories": [
      "Communication",
      "Marketing"
    ],
    "actionCount": 1
  },
  "feishu": {
    "authTypes": [
      "oauth2"
    ],
    "auth": [
      {
        "type": "oauth2"
      }
    ],
    "categories": [
      "Productivity",
      "Storage"
    ],
    "actionCount": 7
  },
  "feishu_app_bot": {
    "authTypes": [
      "custom_credential"
    ],
    "auth": [
      {
        "type": "custom_credential",
        "fields": [
          {
            "key": "appId",
            "label": "App ID",
            "inputType": "text",
            "secret": false,
            "required": true,
            "description": "The Feishu custom app app_id used to fetch tenant_access_token. Find it in the app credentials page at https://open.feishu.cn/app."
          },
          {
            "key": "appSecret",
            "label": "App Secret",
            "inputType": "password",
            "secret": true,
            "required": true,
            "description": "The Feishu custom app app_secret used to fetch tenant_access_token. Copy it from the app credentials page at https://open.feishu.cn/app."
          }
        ]
      }
    ],
    "categories": [
      "Communication"
    ],
    "actionCount": 20
  },
  "feishu_custom_bot": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "Webhook Token",
        "placeholder": "token from Feishu webhook URL",
        "description": "Paste the token path segment from the Feishu webhook URL. The full webhook URL is also accepted. Create a custom bot from https://open.feishu.cn/document/client-docs/bot-v3/add-custom-bot."
      }
    ],
    "categories": [
      "Communication"
    ],
    "actionCount": 5
  },
  "freshdesk": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "FRESHDESK_API_KEY",
        "description": "Freshdesk API key used as the Basic Auth username. Find it in Profile Settings > View API key: https://support.freshdesk.com/support/solutions/articles/215517-how-to-find-your-api-key."
      }
    ],
    "categories": [
      "Communication",
      "Productivity"
    ],
    "actionCount": 4
  },
  "freshservice": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "freshservice_api_key",
        "description": "Freshservice API key used as the HTTP Basic auth username. Find it in your Freshservice profile settings as documented by Freshworks: https://support.freshservice.com/support/solutions/articles/50000000029-where-do-i-find-my-api-key-."
      }
    ],
    "categories": [
      "Communication",
      "Productivity"
    ],
    "actionCount": 6
  },
  "front": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Token",
        "placeholder": "Bearer token",
        "description": "Front Core API token sent as a Bearer token. Create or view tokens in Settings > Developers > API Tokens, or see https://dev.frontapp.com/docs/create-and-revoke-api-tokens."
      }
    ],
    "categories": [
      "Communication",
      "Productivity"
    ],
    "actionCount": 5
  },
  "gemini": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "GEMINI_API_KEY",
        "description": "Gemini API key sent with the x-goog-api-key header. Get it from https://aistudio.google.com/api-keys."
      }
    ],
    "categories": [
      "AI"
    ],
    "actionCount": 8
  },
  "gleap": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "gleap_api_key",
        "description": "Gleap API key sent with the Authorization Bearer header. Create or view it in Project Settings > Security > API Key: https://docs.gleap.io/documentation/server/api-overview."
      }
    ],
    "categories": [
      "Communication",
      "Productivity"
    ],
    "actionCount": 11
  },
  "gmail": {
    "authTypes": [
      "oauth2"
    ],
    "auth": [
      {
        "type": "oauth2"
      }
    ],
    "categories": [
      "Productivity"
    ],
    "actionCount": 46
  },
  "godial": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "Access Token",
        "placeholder": "GODIAL_ACCESS_TOKEN",
        "description": "GoDial external API access token passed as the access_token query parameter. Generate or view it in GoDial at Dashboard -> Integration -> External API, as described in the official integration guide: https://godial.cc/blog/integrating-your-website-or-crm-with-godial-using-api/"
      }
    ],
    "categories": [
      "Communication",
      "Productivity"
    ],
    "actionCount": 5
  },
  "googlecalendar": {
    "authTypes": [
      "oauth2"
    ],
    "auth": [
      {
        "type": "oauth2"
      }
    ],
    "categories": [
      "Productivity",
      "Communication"
    ],
    "actionCount": 37
  },
  "ima": {
    "authTypes": [
      "custom_credential"
    ],
    "auth": [
      {
        "type": "custom_credential",
        "fields": [
          {
            "key": "clientId",
            "label": "Client ID",
            "inputType": "text",
            "secret": false,
            "required": true,
            "description": "The IMA OpenAPI client ID sent with the ima-openapi-clientid header. Get it from the Tencent IMA desktop client."
          },
          {
            "key": "apiKey",
            "label": "API Key",
            "inputType": "password",
            "secret": true,
            "required": true,
            "description": "The IMA OpenAPI API key sent with the ima-openapi-apikey header. Get it from the Tencent IMA desktop client."
          }
        ]
      }
    ],
    "categories": [
      "AI",
      "Productivity"
    ],
    "actionCount": 17
  },
  "intercom": {
    "authTypes": [
      "oauth2"
    ],
    "auth": [
      {
        "type": "oauth2"
      }
    ],
    "categories": [
      "Communication",
      "Productivity"
    ],
    "actionCount": 24
  },
  "jimeng_ai": {
    "authTypes": [
      "custom_credential"
    ],
    "auth": [
      {
        "type": "custom_credential",
        "fields": [
          {
            "key": "accessKeyId",
            "label": "Access Key ID",
            "inputType": "text",
            "secret": false,
            "required": true,
            "placeholder": "AKLT...",
            "description": "Volcengine access key ID used to sign Jimeng AI requests. Create or manage access keys in Volcengine Access Key management: https://console.volcengine.com/iam/keymanage/."
          },
          {
            "key": "secretAccessKey",
            "label": "Secret Access Key",
            "inputType": "password",
            "secret": true,
            "required": true,
            "placeholder": "Your Volcengine secret access key",
            "description": "Volcengine secret access key paired with the access key ID. Volcengine shows it when you create or manage keys: https://www.volcengine.com/docs/6291/65568."
          },
          {
            "key": "sessionToken",
            "label": "Session Token",
            "inputType": "password",
            "secret": true,
            "required": false,
            "placeholder": "Optional STS session token",
            "description": "Optional Volcengine temporary security token used with STS credentials."
          }
        ]
      }
    ],
    "categories": [
      "AI",
      "Design & Media"
    ],
    "actionCount": 28
  },
  "jira": {
    "authTypes": [
      "oauth2",
      "custom_credential"
    ],
    "auth": [
      {
        "type": "oauth2"
      },
      {
        "type": "custom_credential",
        "fields": [
          {
            "key": "baseUrl",
            "label": "Instance URL",
            "inputType": "text",
            "secret": false,
            "required": true,
            "placeholder": "https://jira.example.com",
            "description": "Jira Data Center or Server instance root URL (a deployment context path is supported), without an API endpoint path. Public addresses work by default; private targets (RFC 1918, Tailscale, NetBird, private hostnames) require the self-hosted runtime to enable OOMOL_CONNECT_ALLOW_PRIVATE_NETWORK. Unsafe local, reserved, and cloud-metadata targets always remain blocked."
          },
          {
            "key": "personalAccessToken",
            "label": "Personal access token",
            "inputType": "password",
            "secret": true,
            "required": true,
            "placeholder": "JIRA_PAT",
            "description": "Jira Data Center or Server personal access token."
          }
        ]
      }
    ],
    "categories": [
      "Productivity",
      "Developer Tools"
    ],
    "actionCount": 7
  },
  "linear": {
    "authTypes": [
      "oauth2",
      "api_key"
    ],
    "auth": [
      {
        "type": "oauth2"
      },
      {
        "type": "api_key",
        "label": "Personal API Key",
        "placeholder": "lin_api_...",
        "description": "Linear personal API key sent as the raw Authorization header value. Create or revoke it from Settings > Account > Security & Access."
      }
    ],
    "categories": [
      "Productivity",
      "Developer Tools"
    ],
    "actionCount": 34
  },
  "lingvanex_translation_api": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "LINGVANEX_API_KEY",
        "description": "Lingvanex Translation API key passed as the key query parameter. Create or view your key in the Lingvanex dashboard: https://account.lingvanex.com/dashboard/."
      }
    ],
    "categories": [
      "AI",
      "Productivity"
    ],
    "actionCount": 3
  },
  "luckin_coffee": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "MCP Token",
        "placeholder": "Paste your Luckin Coffee MCP token",
        "description": "The Bearer token shared by Luckin Coffee MCP and CLI. Sign in and create or copy it at https://open.lkcoffee.com/mcp. Keep this token private because it is linked to your Luckin Coffee account session."
      }
    ],
    "categories": [
      "Location",
      "Productivity"
    ],
    "actionCount": 8
  },
  "mcdonalds_cn": {
    "authTypes": [
      "custom_credential"
    ],
    "auth": [
      {
        "type": "custom_credential",
        "fields": [
          {
            "key": "appId",
            "label": "App ID",
            "inputType": "text",
            "secret": false,
            "required": true,
            "placeholder": "McDonald's China AppId",
            "description": "McDonald's China merchant application ID from the Open Platform at https://open.mcd.cn."
          },
          {
            "key": "merchantId",
            "label": "Merchant ID",
            "inputType": "text",
            "secret": false,
            "required": true,
            "placeholder": "McDonald's China MerchantId",
            "description": "McDonald's China merchant ID from the Open Platform at https://open.mcd.cn."
          },
          {
            "key": "signingKey",
            "label": "Signing Key",
            "inputType": "password",
            "secret": true,
            "required": true,
            "placeholder": "McDonald's China signing key",
            "description": "Signing key paired with the AppId and MerchantId from the Open Platform at https://open.mcd.cn. It is used to generate the Sign header."
          },
          {
            "key": "environment",
            "label": "Environment",
            "inputType": "text",
            "secret": false,
            "required": false,
            "placeholder": "prod or uat",
            "description": "McDonald's China API environment. Use prod for https://api.open.mcd.cn or uat for https://api-uat.open.mcdchina.net. Defaults to prod."
          }
        ]
      }
    ],
    "categories": [
      "Location",
      "Data"
    ],
    "actionCount": 7
  },
  "monday": {
    "authTypes": [
      "oauth2",
      "api_key"
    ],
    "auth": [
      {
        "type": "oauth2"
      },
      {
        "type": "api_key",
        "label": "Personal API Token",
        "placeholder": "monday_personal_v2_token",
        "description": "Monday personal V2 API token sent in the Authorization header with an explicit API-Version header. Find it in the monday Developer Center API token tab: https://developer.monday.com/api-reference/docs/authentication."
      }
    ],
    "categories": [
      "Productivity"
    ],
    "actionCount": 64
  },
  "netease_mail": {
    "authTypes": [
      "custom_credential"
    ],
    "auth": [
      {
        "type": "custom_credential",
        "fields": [
          {
            "key": "email",
            "label": "Email Address",
            "inputType": "text",
            "secret": false,
            "required": true,
            "placeholder": "user@163.com",
            "description": "The full personal NetEase Mail address to connect, using 163.com, 126.com, or yeah.net."
          },
          {
            "key": "authorizationCode",
            "label": "Authorization Code",
            "inputType": "password",
            "secret": true,
            "required": true,
            "placeholder": "16-character code",
            "description": "The 16-character client authorization code created after enabling IMAP/SMTP in NetEase Mail settings: https://help.mail.163.com/faqDetail.do?code=d7a5dc8471cd0c0e8b4b8f4f8e49998b374173cfe9171305fa1ce630d7f67ac2a5feb28b66796d3b. This is not the NetEase Mail web login password."
          }
        ]
      }
    ],
    "categories": [
      "Communication",
      "Productivity"
    ],
    "actionCount": 12
  },
  "one_password": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "Connect Access Token",
        "placeholder": "eyJ...",
        "description": "1Password Connect access token sent with the Authorization: Bearer header. Create or copy it from your 1Password Connect Server setup: https://developer.1password.com/docs/connect/get-started."
      }
    ],
    "categories": [
      "Security",
      "Productivity"
    ],
    "actionCount": 6
  },
  "openai": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "sk-proj-...",
        "description": "OpenAI API key used with the Authorization Bearer header. Create or manage it on the API Keys page: https://platform.openai.com/api-keys."
      }
    ],
    "categories": [
      "AI",
      "Developer Tools"
    ],
    "actionCount": 15
  },
  "outlook": {
    "authTypes": [
      "oauth2"
    ],
    "auth": [
      {
        "type": "oauth2"
      }
    ],
    "categories": [
      "Communication",
      "Productivity"
    ],
    "actionCount": 11
  },
  "perplexity": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "PPLX_API_KEY",
        "description": "Perplexity API key used with the Authorization Bearer header. Generate it in Settings > </> API: https://www.perplexity.ai/help-center/en/articles/10352995-api-settings"
      }
    ],
    "categories": [
      "AI"
    ],
    "actionCount": 4
  },
  "pipedrive": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Token",
        "placeholder": "pipedrive_api_token",
        "description": "Pipedrive API token used with the x-api-token header. Find it in Settings > Personal preferences > API: https://pipedrive.readme.io/docs/how-to-find-the-api-token"
      }
    ],
    "categories": [
      "Productivity",
      "Marketing"
    ],
    "actionCount": 27
  },
  "qianfan": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "bce-v3/ALTAK-...",
        "description": "Baidu Qianfan API key used with the Authorization Bearer header. Create it in System Management > API Key: https://cloud.baidu.com/doc/qianfan/s/wmh8l6tnf"
      }
    ],
    "categories": [
      "AI"
    ],
    "actionCount": 25
  },
  "qq_mail": {
    "authTypes": [
      "custom_credential"
    ],
    "auth": [
      {
        "type": "custom_credential",
        "fields": [
          {
            "key": "email",
            "label": "Email Address",
            "inputType": "text",
            "secret": false,
            "required": true,
            "placeholder": "user@qq.com",
            "description": "The full QQ Mail address to connect, such as user@qq.com."
          },
          {
            "key": "authorizationCode",
            "label": "Authorization Code",
            "inputType": "password",
            "secret": true,
            "required": true,
            "placeholder": "16-character code",
            "description": "The 16-character QQ Mail authorization code from QQ Mail web settings > Account and Security after enabling POP3/IMAP/SMTP service: https://help.mail.qq.com/detail/0/1087. This is not the QQ Mail web login password."
          }
        ]
      }
    ],
    "categories": [
      "Communication",
      "Productivity"
    ],
    "actionCount": 12
  },
  "sendgrid": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "SG....",
        "description": "SendGrid API key used with the Authorization Bearer header. Create it in Settings > API Keys: https://www.twilio.com/docs/sendgrid/ui/account-and-settings/api-keys/."
      }
    ],
    "categories": [
      "Communication",
      "Marketing"
    ],
    "actionCount": 4
  },
  "slack": {
    "authTypes": [
      "oauth2"
    ],
    "auth": [
      {
        "type": "oauth2"
      }
    ],
    "categories": [
      "Communication",
      "Productivity"
    ],
    "actionCount": 22
  },
  "telegram": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "Bot Token",
        "placeholder": "123456789:AA...",
        "description": "Create a new bot with @BotFather using /newbot, then paste the generated token here. Telegram documents BotFather at https://core.telegram.org/bots/features#botfather."
      }
    ],
    "categories": [
      "Communication",
      "Social"
    ],
    "actionCount": 50
  },
  "tencent_docs": {
    "authTypes": [
      "oauth2"
    ],
    "auth": [
      {
        "type": "oauth2"
      }
    ],
    "categories": [
      "Productivity",
      "Storage"
    ],
    "actionCount": 16
  },
  "ticktick": {
    "authTypes": [
      "oauth2",
      "api_key"
    ],
    "auth": [
      {
        "type": "oauth2"
      },
      {
        "type": "api_key",
        "label": "Access Token",
        "placeholder": "ticktick_access_token",
        "description": "Paste a TickTick OAuth access token. It is sent with the Authorization Bearer header."
      }
    ],
    "categories": [
      "Productivity"
    ],
    "actionCount": 20
  },
  "torii": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "TORII_API_KEY",
        "description": "Torii API key sent as a Bearer token in the Authorization header. Generate it in Torii Settings > API Access: https://app.toriihq.com/team/settings/apiAccess."
      }
    ],
    "categories": [
      "Productivity",
      "Finance",
      "Security"
    ],
    "actionCount": 9
  },
  "trello": {
    "authTypes": [
      "custom_credential"
    ],
    "auth": [
      {
        "type": "custom_credential",
        "fields": [
          {
            "key": "apiKey",
            "label": "API Key",
            "inputType": "password",
            "secret": true,
            "required": true,
            "placeholder": "Trello API key",
            "description": "Trello API Key from the Key field at https://trello.com/power-ups/admin. Do not use the API Secret or an Atlassian API token here."
          },
          {
            "key": "apiToken",
            "label": "API Token",
            "inputType": "password",
            "secret": true,
            "required": true,
            "placeholder": "Trello API token",
            "description": "Trello API token generated from the Token link beside your API Key at https://trello.com/power-ups/admin. This is different from the API Secret."
          }
        ]
      }
    ],
    "categories": [
      "Productivity"
    ],
    "actionCount": 28
  },
  "twilio": {
    "authTypes": [
      "custom_credential"
    ],
    "auth": [
      {
        "type": "custom_credential",
        "fields": [
          {
            "key": "accountSid",
            "label": "Account SID",
            "inputType": "text",
            "secret": false,
            "required": true,
            "placeholder": "AC...",
            "description": "Twilio Account SID used as the account identifier in API paths. Find it in the Account Info section of https://www.twilio.com/console."
          },
          {
            "key": "authToken",
            "label": "Auth Token",
            "inputType": "password",
            "secret": true,
            "required": true,
            "placeholder": "your_auth_token",
            "description": "Twilio Auth Token used with the Authorization Basic header. Find or rotate it in the Account Info section of https://www.twilio.com/console."
          }
        ]
      }
    ],
    "categories": [
      "Communication"
    ],
    "actionCount": 5
  },
  "twochat": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "YOUR_2CHAT_API_KEY",
        "description": "2Chat API key sent with the X-User-API-Key header. Create or view it from the API Access tab in the 2Chat dashboard: https://app.2chat.io/developers?tab=api-access."
      }
    ],
    "categories": [
      "Communication",
      "Developer Tools"
    ],
    "actionCount": 5
  },
  "wecom_bot": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "Webhook Key",
        "placeholder": "693a91f6-7xxx-4bc4-97a0-0ec2sifa5aaa",
        "description": "Paste the `key` query value from the WeCom bot webhook URL. Create the group bot and copy its webhook URL from the official config guide: https://developer.work.weixin.qq.com/document/path/91770 . The full webhook URL is also accepted."
      }
    ],
    "categories": [
      "Communication"
    ],
    "actionCount": 5
  },
  "whatsapp": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "Access Token",
        "placeholder": "EAAG...",
        "description": "Meta access token used with the Authorization Bearer header. Generate a permanent token from the official WhatsApp Cloud API getting started guide and Meta Business Settings: https://developers.facebook.com/docs/whatsapp/cloud-api/get-started and https://business.facebook.com/latest/settings . The token should include WhatsApp Business messaging and management permissions."
      }
    ],
    "categories": [
      "Communication"
    ],
    "actionCount": 17
  },
  "yuandian": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "API Key",
        "placeholder": "YUANDIAN_API_KEY",
        "description": "Yuan Dian Open Platform API key sent with the X-API-Key header. Connection validation calls the low-cost enterprise search endpoint and consumes 1 Yuan Dian point."
      }
    ],
    "categories": [
      "AI",
      "Data"
    ],
    "actionCount": 23
  },
  "zendesk": {
    "authTypes": [
      "oauth2",
      "api_key"
    ],
    "auth": [
      {
        "type": "oauth2"
      },
      {
        "type": "api_key",
        "label": "API Token",
        "placeholder": "zendesk_api_token",
        "description": "Zendesk API token used with Basic auth as <email>/token together with the account subdomain. Generate it in Admin Center > Apps and integrations > APIs > API tokens."
      }
    ],
    "categories": [
      "Communication",
      "Productivity"
    ],
    "actionCount": 11
  },
  "zhihu": {
    "authTypes": [
      "api_key"
    ],
    "auth": [
      {
        "type": "api_key",
        "label": "Access Secret",
        "placeholder": "zhihu_access_secret",
        "description": "Zhihu Open Platform Access Secret sent with the Authorization: Bearer header. View it in the Zhihu Open Platform profile page: https://developer.zhihu.com/profile."
      }
    ],
    "categories": [
      "AI",
      "Data"
    ],
    "actionCount": 4
  }
};
