#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"

# These paths are regenerated by npm/Expo/Vite/Gradle or belong to local IDE
# tooling. Source files, lockfiles, the tracked Capacitor Android project, and
# deployment rollback state are deliberately not included.
TARGETS=(
  "mobile/node_modules"
  "mobile/.expo"
  "mobile/android"
  "mobile/ios"
  "mobile/dist"
  "mobile/e2e-artifacts"
  "frontend/node_modules"
  "frontend/dist"
  "frontend/.vite"
  "server/node_modules"
  "server/dist"
  "open-connector/node_modules"
  "capacitor/node_modules"
  ".opencode/node_modules"
  ".kilo/node_modules"
)

removed=0
skipped=0

for relative_path in "${TARGETS[@]}"; do
  target="$ROOT_DIR/$relative_path"
  [[ -e "$target" ]] || continue

  # Never let this convenience script remove a tracked path if a generated
  # directory is later promoted into version control.
  tracked_paths="$(git -C "$ROOT_DIR" ls-files -- "$relative_path")"
  if [[ -n "$tracked_paths" ]]; then
    printf 'skip tracked path: %s\n' "$relative_path"
    skipped=$((skipped + 1))
    continue
  fi

  printf 'remove: %s\n' "$relative_path"
  rm -rf -- "$target"
  removed=$((removed + 1))
done

printf 'local cleanup complete: removed %d path(s), skipped %d tracked path(s)\n' "$removed" "$skipped"
