/**
 * lib/socratesWasm.js — lazy loader for the Rust mechanism library.
 *
 * The wasm package (`frontend/wasm/`, generated by `npm run build:wasm`)
 * is imported dynamically so the app keeps working without it: every
 * consumer falls back to its TS implementation when `getSocratesWasm()`
 * returns null.
 *
 * Browser: `initSocratesWasm()` — the generated `init()` fetches the wasm
 * via `new URL(..., import.meta.url)` which Vite resolves natively.
 * Node tests: `initSocratesWasm({ bytes })` — pass a Uint8Array read from
 * the wasm file to sidestep file:// fetch restrictions.
 */

let wasmApi = null;
let wasmInitPromise = null;

/**
 * Loads and instantiates the wasm module (idempotent). Resolves to the
 * module (or null when loading failed); never rejects.
 */
export function initSocratesWasm(opts = {}) {
  if (wasmInitPromise) return wasmInitPromise;
  wasmInitPromise = (async () => {
    const mod = await import('../../wasm/socrates_wasm.js');
    const init = mod.default || mod.init;
    if (opts && opts.bytes) {
      await init(opts.bytes);
    } else {
      await init();
    }
    wasmApi = mod;
    return wasmApi;
  })().catch((err) => {
    wasmInitPromise = null; // allow a later retry
    console.warn('[socrates-wasm] init failed; falling back to TS logic:', err);
    return null;
  });
  return wasmInitPromise;
}

/** The initialized wasm module, or null when not (yet) available. */
export function getSocratesWasm() {
  return wasmApi;
}
