/**
 * lib/socratesWasm.js — lazy loader for the Rust mechanism library.
 *
 * The wasm package (`frontend/wasm/`, generated by `npm run build:wasm`)
 * is imported dynamically so the app keeps working without it: every
 * consumer falls back to its TS implementation when `getSocratesWasm()`
 * returns null.
 *
 * Browser: `initSocratesWasm()` — the generated `init()` fetches the wasm
 * via `new URL(..., import.meta.url)` which Vite resolves natively.
 * Node tests: `initSocratesWasm({ bytes })` — pass a Uint8Array read from
 * the wasm file to sidestep file:// fetch restrictions.
 *
 * `getSocratesWasm()` is sync and returns the loaded module, or null. The
 * first call kicks off `initSocratesWasm()` so the lazy import is wired
 * even when no caller has explicitly awaited it. While the load is in
 * flight, subsequent calls keep returning null and the TS fallback is
 * used; once the wasm resolves, the next call returns the live module.
 */

let wasmApi = null;
let wasmInitPromise = null;
let wasmInitFailed = false;

/**
 * Loads and instantiates the wasm module (idempotent). Resolves to the
 * module (or null when loading failed); never rejects.
 */
export function initSocratesWasm(opts = {}) {
  const hasExplicitBytes = Boolean(opts && opts.bytes);
  if (wasmInitPromise) return wasmInitPromise;
  // A browser/file-based load failure is terminal for this page instance. The
  // synchronous callers intentionally fall back to TypeScript, so retrying on
  // every tool event only creates a noisy, unbounded stream of rejected fetches.
  // An explicit byte-backed load is still allowed to recover (for Node tests or
  // a caller that has supplied a known-good WASM payload).
  if (wasmInitFailed && !hasExplicitBytes) return Promise.resolve(null);
  if (hasExplicitBytes) wasmInitFailed = false;
  wasmInitPromise = (async () => {
    const mod = await import('../../wasm/socrates_wasm.js');
    const init = mod.default || mod.init;
    if (opts && opts.bytes) {
      await init(opts.bytes);
    } else {
      await init();
    }
    wasmApi = mod;
    return wasmApi;
  })().catch((err) => {
    wasmInitFailed = true;
    wasmInitPromise = null; // allow a later retry
    console.warn('[socrates-wasm] init failed; falling back to TS logic:', err);
    return null;
  });
  return wasmInitPromise;
}

/**
 * The initialized wasm module, or null when not (yet) available.
 *
 * Idempotent. The first call after boot also triggers `initSocratesWasm()`
 * so callers that don't explicitly await init still benefit from the
 * Rust-backed code path once the load finishes.
 */
export function getSocratesWasm() {
  if (!wasmApi && !wasmInitPromise) {
    // Fire-and-forget: cache the promise so repeated calls don't re-import.
    initSocratesWasm();
  }
  return wasmApi;
}
